- src/mem/epoch/mod.rs
...to match function argument names
> Updated docs

- src/lib.rs
- src/mem/epoch/garbage.rs
- src/mem/epoch/mod.rs
- src/scoped.rs
Most had a simple workaround or weren't actually even used, so yay!
> Remove a number of #![feature] directives

- src/bin/extra_impls/mpsc_queue.rs
- src/mem/epoch/garbage.rs
- src/mem/epoch/global.rs
- src/sync/atomic_option.rs
> Use Box::{from_raw, into_raw} where appropriate

- src/mem/epoch/garbage.rs
- src/mem/epoch/local.rs
- src/mem/epoch/mod.rs
- src/mem/epoch/participant.rs
This reverts much of 208bf821e70d432d18b2c1284da4aa2eb7bb46fc although
it also includes a few minor refactors.
> Bring back local garbage bags.

- src/sync/treiber_stack.rs
I'd love to just mark `pop` as deprecated, but that's not stable until 1.9, so I added some documentation and feature flagging so that we'd provide a warning where possible.
> rename pop to try_pop with deprecation warning

- src/lib.rs
- src/scoped.rs
> Add scoped thread builder

- src/sync/ms_queue.rs
> Fix ordering bug in MS queue (#100)

- src/sync/ms_queue.rs
- src/sync/seg_queue.rs
- src/sync/treiber_stack.rs
> Implement Drop for TreiberStack, MsQueue, SegQueue

- README.md
Closes #152 
I would like to merge it with only one approval; it's an obvious documentation bug.
> Fix a documentation bug (#152)

- README.md
This is basically to avoid confusion and issues such as #161.
> Add notice about rewrite

- Cargo.toml
- README.md
- src/lib.rs
I updated the crate's top-level documentation to better reflect the current status.
> Update the top-level crate doc

- src/ms_queue.rs
> Drop guard before sleeping

- src/treiber_stack.rs
Fixes #191. This is also a security issue that could lead to remote code execution via a use-after-free, but crossbeam is still in development, so I wouldn't say this is very serious. Thoughts?
> Fix UAF in TreiberStack

- Cargo.toml
- crossbeam-epoch/Cargo.toml
- crossbeam-epoch/src/atomic.rs
- crossbeam-epoch/src/collector.rs
- crossbeam-epoch/src/default.rs
- crossbeam-epoch/src/lib.rs
- crossbeam-epoch/src/sync/list.rs
- crossbeam-epoch/src/sync/queue.rs
- crossbeam-skiplist/Cargo.toml
- crossbeam-skiplist/src/lib.rs
- crossbeam-utils/Cargo.toml
- crossbeam-utils/src/atomic/atomic_cell.rs
- crossbeam-utils/src/lib.rs
- src/lib.rs
- src/ms_queue.rs
- src/seg_queue.rs
- src/treiber_stack.rs
Also updates `crossbeam-utils` in some crates. I'll follow up with another PR that fixes the whole dependency tree.
Closes #194
> Rename use_std feature to std

- crossbeam-channel/Cargo.toml
- crossbeam-deque/Cargo.toml
> Fix a typo in Cargo.toml

- .travis.yml
This should make our builds somewhat faster.
> Use Cargo cache on Travis

- crossbeam-epoch/benches/defer.rs
- crossbeam-epoch/benches/flush.rs
- crossbeam-epoch/benches/pin.rs
> Fix benchmark suite

- CHANGELOG.md
- Cargo.toml
- crossbeam-channel/CHANGELOG.md
- crossbeam-channel/Cargo.toml
- crossbeam-deque/CHANGELOG.md
- crossbeam-deque/Cargo.toml
- crossbeam-epoch/CHANGELOG.md
- crossbeam-epoch/Cargo.toml
- crossbeam-skiplist/CHANGELOG.md
- crossbeam-skiplist/Cargo.toml
- crossbeam-utils/CHANGELOG.md
- crossbeam-utils/Cargo.toml
Let's release new versions of crates.
> Prepare v0.5.0

- crossbeam-channel/src/channel.rs
- crossbeam-channel/src/waker.rs
> Optimize channel disconnection

- ci/crossbeam-channel.sh
- ci/crossbeam-deque.sh
- ci/crossbeam-epoch.sh
- ci/crossbeam-skiplist.sh
- ci/crossbeam-utils.sh
- ci/crossbeam.sh
- ci/dependencies.sh
- crossbeam-channel/src/channel.rs
- crossbeam-channel/src/select.rs
- crossbeam-deque/src/lib.rs
- crossbeam-epoch/src/collector.rs
- crossbeam-epoch/src/deferred.rs
- crossbeam-epoch/src/guard.rs
- crossbeam-skiplist/src/base.rs
- crossbeam-skiplist/src/lib.rs
- crossbeam-skiplist/src/map.rs
- crossbeam-skiplist/src/set.rs
- crossbeam-utils/src/sync/parker.rs
- crossbeam-utils/src/thread.rs
- src/lib.rs
- src/seg_queue.rs
- src/sharded_lock.rs
- src/wait_group.rs
> Implement missing Debug and docs

- crossbeam-channel/src/select.rs
- crossbeam-channel/src/select_macro.rs
Closes #257 
@mchesser Thank you for the suggestions on how to improve docs! How does this look?
> channel: Improve docs for selection

- crossbeam-channel/Cargo.toml
- crossbeam-channel/src/channel.rs
- crossbeam-channel/src/flavors/after.rs
- crossbeam-channel/src/flavors/array.rs
- crossbeam-channel/src/flavors/list.rs
- crossbeam-channel/src/flavors/never.rs
- crossbeam-channel/src/flavors/tick.rs
- crossbeam-channel/src/flavors/zero.rs
- crossbeam-channel/src/select.rs
- crossbeam-channel/src/waker.rs
There are no big changes here - this is just cleanup (with possible performance improvements as a consequence).
> Simplify non-blocking select and tick()

- crossbeam-channel/src/flavors/array.rs
Just some small optimizations.
> channel: optimize the array flavor

- crossbeam-channel/benchmarks/README.md
- crossbeam-channel/src/flavors/list.rs
> channel: update benchmarks

- crossbeam-channel/Cargo.toml
- crossbeam-channel/src/lib.rs
- crossbeam-channel/src/utils.rs
We don't need strong randomness anyway so this is one dependency fewer.
> channel: remove rand dependency

- crossbeam-channel/src/select.rs
- crossbeam-utils/src/lib.rs
- src/lib.rs
Just a simple missing addition discovered through Clippy.
> channel: impl Default for Select

- CHANGELOG.md
- Cargo.toml
- README.md
- crossbeam-channel/CHANGELOG.md
- crossbeam-channel/Cargo.toml
- crossbeam-deque/CHANGELOG.md
- crossbeam-deque/Cargo.toml
- crossbeam-deque/README.md
- crossbeam-epoch/CHANGELOG.md
- crossbeam-epoch/Cargo.toml
- crossbeam-queue/CHANGELOG.md
- crossbeam-queue/Cargo.toml
- crossbeam-queue/README.md
- crossbeam-queue/src/lib.rs
- crossbeam-skiplist/Cargo.toml
- crossbeam-utils/CHANGELOG.md
- crossbeam-utils/Cargo.toml
- crossbeam-utils/README.md
We're ready to release new versions of all crates! 🎉
> Prepare a new Crossbeam release

- crossbeam-channel/tests/mpsc.rs
Depends on #322.
Updates  #321.
>  Cleanup panicking test threads

- crossbeam-utils/src/atomic/atomic_cell.rs
> Fix the AtomicCell::compare_and_swap example

- crossbeam-utils/src/atomic/atomic_cell.rs
> Use acquire-release orderings in AtomicCell

- crossbeam-channel/src/counter.rs
- crossbeam-channel/src/flavors/array.rs
- crossbeam-channel/src/flavors/list.rs
- crossbeam-channel/src/flavors/zero.rs
- crossbeam-channel/src/waker.rs
- crossbeam-channel/tests/array.rs
- crossbeam-channel/tests/list.rs
- crossbeam-channel/tests/zero.rs
Just a minor improvement + more tests.
> channel: optimize disconnection

- crossbeam-channel/Cargo.toml
- crossbeam-channel/benches/crossbeam.rs
> channel: add microbenchmarks

- crossbeam-channel/tests/golang.rs
Add a test for `crossbeam-channel` according to go channel test [sieve1](https://github.com/golang/go/blob/master/test/chan/sieve1.go)
> Add Test sieve1

- LICENSE-MIT
- crossbeam-channel/LICENSE-MIT
- crossbeam-deque/LICENSE-MIT
- crossbeam-epoch/LICENSE-MIT
- crossbeam-queue/LICENSE-MIT
- crossbeam-skiplist/LICENSE-MIT
- crossbeam-utils/LICENSE-MIT
> Add copyright notice

- crossbeam-channel/tests/golang.rs
Porting the [goroutines](https://github.com/golang/go/blob/master/test/chan/goroutines.go) test from the Go lang repository.
Part of https://github.com/crossbeam-rs/crossbeam/issues/201
Any help would be appreciated.
> Port test from Go lang - goroutines

- crossbeam-channel/src/select.rs
> Add Select::{clear,disable}

- crossbeam-channel/src/flavors/array.rs
- crossbeam-channel/src/flavors/list.rs
Fixes the following problem reported by @leodasvacas:
https://discordapp.com/channels/569610676205781012/569610676205781015/581517999773712398
> Perform try_X after X_timeout times out

- crossbeam-utils/src/atomic/atomic_cell.rs
- crossbeam-utils/tests/atomic_cell.rs
Closes #388 
@mchesser Could you perhaps confirm that this resolves the bug for you?
> Fix a bug in AtomicCell with garbage padding

- ci/crossbeam-channel.sh
- ci/crossbeam-deque.sh
- ci/crossbeam-epoch.sh
- ci/crossbeam-queue.sh
- ci/crossbeam-skiplist.sh
- ci/crossbeam-utils.sh
- ci/crossbeam.sh
> Allow warnings on nightly

- crossbeam-channel/src/select_macro.rs
https://github.com/crossbeam-rs/crossbeam/issues/404
> chore: fix macro clippy lint

- crossbeam-channel/CHANGELOG.md
- crossbeam-channel/Cargo.toml
- crossbeam-epoch/CHANGELOG.md
- crossbeam-epoch/Cargo.toml
- crossbeam-utils/CHANGELOG.md
- crossbeam-utils/Cargo.toml
Closes #475 
Sorry for a mistake in release.  I yanked bad versions and I will release new versions of the affected crates.
> Release new versions

- crossbeam-deque/src/lib.rs
The implementation for `Injector::len()` was simply copied from `SegQueue::len()`.
> Add len() methods to deque

- crossbeam-utils/src/sync/parker.rs
@carllerche Can you review this PR and confirm the API fits your use case?
> Conversion of Parker/Unparker into/from a raw pointer

- Cargo.toml
- crossbeam-channel/Cargo.toml
- crossbeam-deque/Cargo.toml
- crossbeam-epoch/Cargo.toml
- crossbeam-queue/Cargo.toml
- crossbeam-skiplist/Cargo.toml
- crossbeam-utils/Cargo.toml
Updates major version of 2 private (dev-)dependencies.
> Update scopeguard to 1, rand to 0.7

- .github/workflows/ci.yml
- bors.toml
- ci/crossbeam-epoch.sh
- crossbeam-channel/examples/stopwatch.rs
Replaces #518 (changing bors-ng configuration from a forked branch doesn't seem to work well...)
> Enable tests on Windows on CI

- Cargo.toml
- crossbeam-channel/Cargo.toml
- crossbeam-deque/Cargo.toml
- crossbeam-epoch/Cargo.toml
- crossbeam-queue/Cargo.toml
- crossbeam-skiplist/Cargo.toml
- crossbeam-utils/Cargo.toml
This PR upgrades the dependencies as suggested by `cargo upgrade`.
> Upgrade all dependencies

- .github/workflows/ci.yml
- Cargo.toml
- ci/clippy.sh
- crossbeam-channel/Cargo.toml
- crossbeam-channel/src/err.rs
- crossbeam-channel/src/utils.rs
- crossbeam-deque/Cargo.toml
- crossbeam-deque/src/deque.rs
- crossbeam-epoch/Cargo.toml
- crossbeam-epoch/src/atomic.rs
- crossbeam-epoch/src/deferred.rs
- crossbeam-queue/Cargo.toml
- crossbeam-skiplist/Cargo.toml
- crossbeam-skiplist/src/base.rs
- crossbeam-skiplist/src/map.rs
- crossbeam-utils/Cargo.toml
- crossbeam-utils/src/atomic/atomic_cell.rs
- crossbeam-utils/src/sync/wait_group.rs
Now CI runs `clippy`!
Closes #509
> Clippy in CI

- crossbeam-utils/src/cache_padded.rs
helps the compiler to pre-compute some quantities
> add support of a constant initialization routine

- crossbeam-channel/src/select_macro.rs
This hack is no longer needed.
> Remove crossbeam_channel_delegate hack

- crossbeam-utils/src/atomic/atomic_cell.rs
- crossbeam-utils/src/backoff.rs
- crossbeam-utils/src/sync/parker.rs
- crossbeam-utils/src/sync/sharded_lock.rs
- crossbeam-utils/src/sync/wait_group.rs
- crossbeam-utils/src/thread.rs
* Document some panics and errors
* Use intra-doc links
* Minor doc improvements
> Improve docs for crossbeam-utils

- README.md
- crossbeam-channel/README.md
- crossbeam-deque/README.md
- crossbeam-epoch/README.md
- crossbeam-queue/README.md
- crossbeam-utils/README.md
> Update version numbers in readme

- .github/workflows/ci.yml
- ci/check-features.sh
Refs: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onschedule
> Run CI on a regular basis

- crossbeam-utils/src/atomic/seq_lock_wide.rs
It's quite an embarrassing bug by me...
> Fix a bug in seq_lock_wide (closes #595)

- crossbeam-skiplist/src/base.rs
https://github.com/crossbeam-rs/crossbeam/runs/1630617165?check_suite_focus=true
> Fix clippy warnings

- src/lib.rs
> Remove re-export hack

- crossbeam-channel/src/flavors/array.rs
- crossbeam-channel/src/flavors/at.rs
- crossbeam-channel/src/flavors/never.rs
- crossbeam-channel/src/flavors/tick.rs
- crossbeam-channel/src/flavors/zero.rs
- crossbeam-utils/src/atomic/atomic_cell.rs
https://github.com/crossbeam-rs/crossbeam/runs/1891613088?check_suite_focus=true
> Ignore clippy::unnecessary_wraps lint

- crossbeam-deque/src/deque.rs
https://github.com/crossbeam-rs/crossbeam/runs/2198421682?check_suite_focus=true
> Format with rustfmt

- crossbeam-deque/src/deque.rs
Clippy doesn't like this pattern:
```
for i in 0..batch_size {
...
batch_size = i;
...
}
```
because it can trick readers into thinking the loop condition might be
modified during iteration. This avoids the warning by explicitly making
a new variable for the end condition of the loop.
> Address clippy warning

- crossbeam-channel/src/waker.rs
Use iter instead of index to avoid bounds check.
> avoid bounds check in Waker::try_select method

- crossbeam-channel/src/waker.rs
- crossbeam-channel/tests/after.rs
- crossbeam-channel/tests/array.rs
- crossbeam-channel/tests/iter.rs
- crossbeam-channel/tests/list.rs
- crossbeam-channel/tests/mpsc.rs
- crossbeam-channel/tests/never.rs
- crossbeam-channel/tests/select.rs
- crossbeam-channel/tests/tick.rs
- crossbeam-channel/tests/zero.rs
- crossbeam-epoch/src/internal.rs
- crossbeam-queue/tests/array_queue.rs
- crossbeam-queue/tests/seg_queue.rs
- crossbeam-skiplist/src/base.rs
- crossbeam-skiplist/tests/map.rs
Addresses the newly added clippy warnings.
> Fix newly added clippy warnings

- no_atomic.rs
https://github.com/crossbeam-rs/crossbeam/runs/3152796151?check_suite_focus=true
> Update list of targets that do not support Atomic*64

- crossbeam-deque/CHANGELOG.md
- crossbeam-deque/Cargo.toml
- crossbeam-deque 0.7.3 -> 0.7.4
> v0.7: Prepare for the next release

- crossbeam-epoch/build.rs
- crossbeam-queue/build.rs
- crossbeam-skiplist/build.rs
- crossbeam-utils/build.rs
> Add comment about cfgs to build script

- .github/workflows/ci.yml
- ci/clippy.sh
- ci/miri.sh
- crossbeam-channel/benches/crossbeam.rs
- crossbeam-channel/tests/golang.rs
- crossbeam-channel/tests/mpsc.rs
- crossbeam-channel/tests/ready.rs
- crossbeam-channel/tests/select.rs
- crossbeam-channel/tests/select_macro.rs
- crossbeam-deque/tests/fifo.rs
- crossbeam-deque/tests/injector.rs
- crossbeam-deque/tests/lifo.rs
- crossbeam-epoch/benches/pin.rs
- crossbeam-epoch/src/deferred.rs
- crossbeam-epoch/src/sync/queue.rs
- crossbeam-skiplist/tests/base.rs
- crossbeam-skiplist/tests/map.rs
I intentionally allow some lint for the same reason as described in #696.
> Apply clippy to tests and examples

- ci/miri.sh
It slows down tests: https://github.com/rust-lang/miri/issues/1702
> Avoid -Zmiri-disable-isolation if possible

- .github/workflows/ci.yml
- .github/workflows/release.yml
Refs: [create-gh-release-action](https://github.com/taiki-e/create-gh-release-action)
> Create GitHub release automatically

- crossbeam-channel/src/flavors/array.rs
- crossbeam-channel/src/flavors/list.rs
- crossbeam-channel/src/flavors/zero.rs
- crossbeam-channel/src/select.rs
https://github.com/crossbeam-rs/crossbeam/runs/4769682775?check_suite_focus=true
> Fix unreachable_pub warning

- crossbeam-deque/src/lib.rs
https://github.com/crossbeam-rs/crossbeam/runs/4904085171?check_suite_focus=true
> Ignore buggy clippy::question_mark lint

- ci/miri.sh
> Enable -Zmiri-symbolic-alignment-check and -Zmiri-check-number-validity in miri CI

- crossbeam-utils/src/atomic/atomic_cell.rs
- crossbeam-utils/tests/atomic_cell.rs
refs:
- [AtomicUsize::fetch_nand](https://doc.rust-lang.org/core/sync/atomic/struct.AtomicUsize.html#method.fetch_nand)
- [AtomicUsize::fetch_max](https://doc.rust-lang.org/core/sync/atomic/struct.AtomicUsize.html#method.fetch_max)
- [AtomicUsize::fetch_min](https://doc.rust-lang.org/core/sync/atomic/struct.AtomicUsize.html#method.fetch_min)
> Add AtomicCell::{fetch_nand,fetch_max,fetch_min}

- crossbeam-channel/src/channel.rs
- crossbeam-channel/src/flavors/at.rs
- crossbeam-channel/src/flavors/tick.rs
- crossbeam-channel/src/select.rs
- crossbeam-channel/src/utils.rs
> channel: Do not panic on very large timeout

- crossbeam-channel/tests/golang.rs
Port of the [chan.go](https://github.com/golang/go/blob/master/test/ken/chan.go) test.
Part of #201
> Golang test chan

- .github/workflows/ci.yml
- ci/miri.sh
- crossbeam-utils/CHANGELOG.md
- crossbeam-utils/Cargo.toml
- tools/publish.sh
- crossbeam-utils 0.8.9 -> 0.8.10
- Fix unsoundness of `AtomicCell` on types containing niches. (#834)
This fix contains breaking changes, but they are allowed because this is a soundness bug fix. See #834 for more.
> Prepare for the next release

- crossbeam-channel/src/channel.rs
https://github.com/crossbeam-rs/crossbeam/runs/7479566226?check_suite_focus=true
> channel: Attempt to fix flaky doctest

- .cirrus.yml
- .github/bors.toml
- .github/workflows/ci.yml
- ci/docs.sh
- ci/test.sh
> Run tests on real aarch64 hardware

- .cirrus.yml
- .github/bors.toml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- ci/dependencies.sh
- ci/rustfmt.sh
- crossbeam-utils/src/cache_padded.rs
- Use dtolnay/rust-toolchain action
- Use cargo-minimal-versions to minimal versions check
- Add macOS to CI (x86_64 and aarch64)
- Fix CachePadded doctest on arm
Closes #642
Fixes #668
> Clean up CI config

- crossbeam-utils/src/sync/wait_group.rs
https://github.com/crossbeam-rs/crossbeam/runs/7571501151?check_suite_focus=true
> Miri: Fix thread leaks in WaitGroup doctest

- Cargo.toml
https://github.com/crossbeam-rs/crossbeam/runs/7595350691?check_suite_focus=true
> Update patch to once_cell

- Cargo.toml
- crossbeam-utils/src/sync/wait_group.rs
https://github.com/crossbeam-rs/crossbeam/runs/7849290051?check_suite_focus=true
> Miri: Fix thread leak in WaitGroup doctest

- .github/workflows/ci.yml
https://github.com/taiki-e/cache-cargo-install-action
> Use cache-cargo-install-action to install cargo-careful

- crossbeam-channel/tests/mpsc.rs
- crossbeam-channel/tests/ready.rs
- crossbeam-channel/tests/select.rs
- crossbeam-channel/tests/select_macro.rs
- crossbeam-epoch/src/deferred.rs
- crossbeam-skiplist/src/base.rs
- crossbeam-utils/src/sync/sharded_lock.rs
- no_atomic.rs
CI needs to be appeased, it seems.
> chore: fix CI

- crossbeam-epoch/build.rs
- crossbeam-queue/build.rs
- crossbeam-skiplist/build.rs
- crossbeam-utils/build.rs
- crossbeam-utils/src/atomic/consume.rs
> Always use load(Acquire) for load_consume on Miri/TSan

- crossbeam-utils/src/thread.rs
- crossbeam-utils/tests/thread.rs
> Use own unix::JoinHandleExt trait

- ci/miri.sh
- ci/san.sh
- crossbeam-skiplist/tests/base.rs
Fixes #614
This is not a bug in SkipList itself, but in our test code.
> skiplist: Fix memory leaks in SkipList test

- crossbeam-utils/src/sync/mod.rs
- crossbeam-utils/src/sync/parker.rs
- crossbeam-utils/tests/parker.rs
> utils: Return UnparkReason from park_{timeout,deadline}

- crossbeam-queue/src/array_queue.rs
- crossbeam-queue/src/seg_queue.rs
channel already implements them.
> queue: Implement {,Ref}UnwindSafe

- crossbeam-channel/src/channel.rs
- crossbeam-channel/src/counter.rs
- crossbeam-channel/src/flavors/array.rs
- crossbeam-channel/src/flavors/list.rs
- crossbeam-channel/src/flavors/zero.rs
- crossbeam-channel/src/lib.rs
- crossbeam-deque/src/deque.rs
- crossbeam-deque/src/lib.rs
- crossbeam-epoch/src/atomic.rs
- crossbeam-epoch/src/deferred.rs
- crossbeam-epoch/src/guard.rs
- crossbeam-epoch/src/internal.rs
- crossbeam-epoch/src/lib.rs
- crossbeam-epoch/src/sync/list.rs
- crossbeam-queue/src/lib.rs
- crossbeam-queue/src/seg_queue.rs
- crossbeam-skiplist/src/base.rs
- crossbeam-skiplist/src/lib.rs
- crossbeam-utils/src/atomic/atomic_cell.rs
- crossbeam-utils/src/lib.rs
- crossbeam-utils/src/sync/once_lock.rs
- crossbeam-utils/src/sync/parker.rs
- src/lib.rs
This is being discussed to become the default in future editions.
> Apply unsafe_op_in_unsafe_fn lint

- crossbeam-channel/benchmarks/flume.rs
- crossbeam-channel/benchmarks/mpsc.rs
- crossbeam-channel/src/utils.rs
- crossbeam-channel/tests/thread_locals.rs
- crossbeam-epoch/src/default.rs
This is available since Rust 1.59 (https://github.com/rust-lang/rust/pull/91355).
> Use const thread_local

- crossbeam-channel/src/flavors/array.rs
- crossbeam-queue/src/array_queue.rs
`cap` stores the channel capacity, the number of slots in `buffer`. There's no additional cost to extracting the length of a slice, so remove `cap` and use `buffer.len()` instead.
> array::Channel: remove redundant cap field

- crossbeam-channel/src/flavors/list.rs
Per https://github.com/rust-lang/rust/pull/121646#discussion_r1503682759.
> Document potential memory leak in unbounded channel

- .github/dependabot.yml
- .github/workflows/ci.yml
> ci: Remove workaround for fixed AArch64 Linux runner bug
