crossbeam-rs/crossbeam

src/lib.rs, src/mem/cache_padded.rs
32-bit linux had some types where the alignment of `CachedPadded<T>` was
less than that of T, causing tests to fail and possible problems.
=> Ensure that CachePadded has high alignment.

src/mem/epoch/participant.rs
Dear Aaron,
- I am new to this library, so my understanding of the memory orderings used in this library may be flawed, and this PR may introduce a bug. Could you possibly review this PR?
- I would to like check the correctness by testing, but I don't know how to do benchmark. What can I do before submitting PR to ensure the PR's correctness?
Thank you,
Jeehoon
--
When exiting a critical section, `in_critical`, which tracks the number
of reentrants, is decremented.  Originally, the memory ordering of the
decrement was Release if the decremented value is bigger than 1, but
this commit changes the threshold to 0.  This is because the only reason
for the Release ordering is for `try_collect` to see the change, but it
only distinguishes nonzero values from the zero.
=> Relax mem ordering more when exiting a crit. sect.

src/scoped.rs
As, funny enough, arc mentions on IRC, the copy here to i meant that we
didn't actually need the Box at all. Really, Arc<T> is what should have
been used here.
=> Change scoped example to use Arc instead of Box

src/sync/ms_queue.rs, src/sync/seg_queue.rs
Noticed two typos when reading the docs, so this is a small PR to fix them up. Thanks for making an awesome crate!
=> Fix small typos in documentation

src/sync/ms_queue.rs
Was someone typing in parallel? The result seems to be out of order... :stuck_out_tongue_closed_eyes:
=> DOC: Fix some typos

Cargo.toml, src/sync/chase_lev.rs, src/sync/mod.rs
This adds an implementation of the Chase-Lev work-stealing deque which was found
in the standard library long ago. This implementation has been modified to use
crossbeam's memory reclamation scheme instead of a custom "buffer pool", so it
should actually free data now!
=> Add an implementation of the Chase-Lev deque

src/bin/bench.rs, src/mem/cache_padded.rs, src/mem/epoch/mod.rs, src/sync/ms_queue.rs, src/sync/seg_queue.rs
This involves renaming the existing `pop` method in all queues to
`try_pop`, which is useable for non-blocking `pop` attempts.
The new `pop` method in `MsQueue` will block until data is available.
There's relatively little overhead on purely non-blocking use-cases, and
most uses of queues want blocking functionality anyway.
Closes #10.
r? @alexcrichton @huonw
=> Add blocking support to `MsQueue`.

src/sync/ms_queue.rs, src/sync/seg_queue.rs
The latter is particularly important, as previously SegQueue would allow
sending, e.g., Rc<_> across threads.
=> Relax T: Sync for MsQueue<T>: Send/Sync, and add T: Send for SegQueue.

src/mem/epoch/garbage.rs
The collect function in ConcBag is unsound - it's possible for a thread inserting into the linked list at the same time a thread enters collect to make an insertion that isn't visible. This happens when the collecting thread loads head (previously line 127), then thread b successfully completes the CAS to update head (line 122), then the collecting thread stores nullptr to head (previously line 128) and continues using a stale value for head. Moving to an atomic swap means that the CAS will not race with the store - either the CAS will complete first and that value will be visible in the swap, or the swap will complete first and the CAS will fail.
A similar issue happens when two threads attempt to collect at the same time, and is fixed by this as well.
=> Fixing race condition in garbage collection

src/mem/epoch/garbage.rs, src/mem/epoch/participant.rs, src/mem/epoch/participants.rs
Fix two bugs that were preventing memory reclamation from occurring and another bug exposed by reclaiming the memory.
In my brief testing, performance impact is fairly small (and positive sometimes?). Might be worth regenerating the doc graphs anyways, though?
=> Fix bugs preventing memory reclamation

src/sync/chase_lev.rs
The old `std::sync::deque` module, and the `deque` crate descended from it, require only that `T` implement `Send` in order for `Deque<T>` to implement `Send` and `Sync`. This crate's `chase_lev` module, however, currently requires `T` also to be `Sync`, making this example fail to compile.
#![feature(optin_builtin_traits)]
extern crate crossbeam;
extern crate deque;
use std::thread;
struct Unsynced;
impl !Sync for Unsynced { }
#[test]
fn deque_crate_unsynced() {
use deque;
let (worker, stealer) = deque::new();
let handle = thread::spawn(move || {
loop {
match stealer.steal() {
deque::Stolen::Data(_) => {
break;
}
_ => {}
}
}
});
worker.push(Unsynced);
handle.join().unwrap();
}
#[test]
fn chase_lev_mod_unsynced() {
use crossbeam::sync::chase_lev;
let (mut worker, stealer) = …
=> Relax the requirements for `Deque<T>` to be `Send` and `Sync`.

src/mem/epoch/garbage.rs, src/mem/epoch/local.rs, src/mem/epoch/mod.rs, src/mem/epoch/participant.rs, src/mem/epoch/participants.rs
This commit closes two major holes, one related to the use of local
garbage bags, and the other to reclaiming participant data from exited
threads. After making these changes, I am no longer able to reproduce
segfaults or assertion failures. (I had previously build some aggressive
testing that was able to consistently segfault in a few seconds on every try.)
The use of local bags was creating a problem in which garbage could be
collected too early. It's crucial that when `unlinked` is called, the
data to be reclaimed is associated with the *current global
epoch* (and **not** the current local snapshot of the epoch). The reason
is that other threads may have outstanding pointers to the data, and may
be an epoch ahead; when the thread calling `unlinked` unpins, the epoch
could move forward …
=> Fix multiple segfault-causing bugs

src/sync/seg_queue.rs
This removes a direct assignment to uninitialized memory. The assignment causes the program to try and drop the variable, which can cause issues - see #44 for an example.
=> Fixed direct assignment to uninitialized memory

src/sync/seg_queue.rs
Unlink segments after the head advances past them
=> Made SegQueue free memory

src/mem/epoch/participant.rs
In try_collect(), it is important to reclaim memory from two epochs
ago *before* advancing the local epoch. As soon as the local epoch has
been advanced, another thread could advance the epoch and start
putting garbage in that same bag.
Closes #46.
=> Don't advance the epoch in try_collect until after doing the collection.

src/sync/seg_queue.rs
This combines the ready block and the data block in seq queue. Combining these has some good cache properties -
- Loads of the ready variable in pull will likely read the data into the cache, and same with loads of the data in push.
- Writes to the data and ready variable may well be combined.
- Elements are farther apart in the cache, so writes from pushers won't invalidate reads from pullers as much.
In my basic (and somewhat variable) tests, this saw performance gains of:
- mpmc: 5-15% increase
- spmc: 0-5% increase
- spsc: 15-35% increase
Also, this version is generally more consistent performance-wise probably due to less cache thrashing.
=> Combined ready and data arrays in seg_queue

src/sync/seg_queue.rs
A pull request of mine accidentally removed memory reclamation from seg_queue, this adds it back.
=> Re-introduce gc to seg-queue

src/lib.rs
`std`'s `thead::spawn` requires the passed function to be bound by `Send` to avoid bad things like passing `UnsafeCell` between threads. The goal of `spawn_unsafe` is to remove the closure lifetime bound, but in its current version, it also removes the `Send` bound, preventing the compiler from catching a number of potential bugs. This patch adds back `Send`, and fixes #54.
=> Align spawn_unsafe with thread::spawn by requiring Send

src/sync/chase_lev.rs
I wasn't sure what to do with (most of) the orderings in resize-related methods, so I just left them as SeqCst.
It would be nice to have benchmarks here. I am also not sure that my merging of techniques from the two papers is completely accurate, although all tests pass on my machine.
I additionally changed the operations on top and bottom to be wrapping, but this shouldn't cause any issues.
=> Use more relaxed orderings in chase_lev

src/sync/arc_cell.rs, src/sync/atomic_reference.rs, src/sync/mod.rs
See https://github.com/sfackler/log4rs/commit/5ed2895bfe2ac92e30a4a5506bde98081bc85cce for a usage example.
I'm not sure `AtomicReference` is the right name - I stole it from Java, but we might want this to be called something else to indicate that it's tied up with `Arc`.
It's also a bit sketchy that we assume that `Arc<T>` is the same size as `usize`, but that seems preferable to defining a new smart pointer just for this.
=> Add an AtomicReference type

src/bin/extra_impls/mpsc_queue.rs, src/mem/cache_padded.rs, src/mem/epoch/atomic.rs, src/mem/epoch/garbage.rs, src/mem/epoch/global.rs, src/mem/epoch/guard.rs, src/mem/epoch/local.rs, src/mem/epoch/mod.rs, src/mem/epoch/participant.rs, src/mem/epoch/participants.rs, src/scoped.rs, src/sync/arc_cell.rs, src/sync/atomic_option.rs, src/sync/chase_lev.rs, src/sync/ms_queue.rs, src/sync/seg_queue.rs, src/sync/treiber_stack.rs
This commit implements `std::fmt::Debug` for all public types. In most cases,
this was simply adding `#[derive(Debug)]` to the type and the types of its
members. However, there are two exceptions, where `Debug` is implemented
manually because it cannot be derived: (1) `Scope<'a>`, which uses `FnBox` which
is not `Debug`, and (2) `ScopedJoinHandle<T>`, which uses `JoinState` which uses
`std::thread::JoinHandle<T>` which is not `Debug`.
Fixes #62.
=> Implement the `Debug` trait for all public types

README.md
So the readme needs less updating as the package evolves.
=> Use version without patch version in example

src/sync/ms_queue.rs
If you create an `MsQueue` with `MsQueue::new()`, then call `push()`, the first thing that is called is `tail.is_data()`.
This function reads from the value of `tail.payload` whose content is set `mem::uninitialized()` by the `new()` function.
In the tests the content of `tail.payload` ends up being filled with 0s, so there's no problem. In my real-world application though, the enum discriminant that chooses between the enum variants `Payload::Data` and `Payload::Blocked` is `1184` , which leads to a crash.
This PR fixes that so that it no longer crashes. In reality though, the code after the fix is still technically undefined behavior since you're still reading partially uninitialized memory.
=> Fix reading uninitialized data in ms_queue

src/sync/ms_queue.rs
`Signal.ready` is being used to guard access to the data slot. This
requires using acquire / release ordering vs. relaxed.
I believe that the original code was written with the assumption that
`thread::park() / unpark()` was able to provide the necessary ordering,
but this is not true given that park() can spuriously wakeup, which
means that there is a chance (although, a small one) for the memory to
not be in a consistent state.
Fixes #97
=> Fixes ordering bug in ms queue

src/mem/epoch/guard.rs
This fixes a bug where entering nested epochs could cause the
epoch to advance invalidly. Closes #105.
=> Don't try to gc except when we have just entered an epoch.

README.md
The documentation at http://aturon.github.io/crossbeam-doc/crossbeam/ looks stale so I propose that docs.rs is used instead.
=> Replace outdated doc link with docs.rs

src/sync/seg_queue.rs
we need a way to quickly test if the queue is empty without taking the action to pull the queue
=> add is_empty() interface for SeqQueue

src/sync/ms_queue.rs
The problem is that we set `ready` to `true` and then again dereference `signal` to wake up the thread:
```rust
(*signal).ready.store(true, Relaxed);
// Just before we unpark the thread, someone else might do it and
// that thread might destroy the stack-allocated signal.
(*signal).thread.unpark();
```
We must acquire a `Thread` *before* setting `ready` to `true`, and only then unpark the thread without dereferencing `signal`.
cc @Vtec234
This *probably* fixes #107.
=> Fix use-after-free when waking up a blocked thread

src/sync/chase_lev.rs
This makes it possible to use `chase_lev` as a drop-in replacement for
the deque in the `deque` crate, especially in `rayon`
=> Change mutability in `push` and `try_pop`

src/sync/chase_lev.rs
The `try_pop` function's control flow is simplified.  I think this version is more readable than before.
A downside is that it diverges from the implementation in this [paper](http://www.di.ens.fr/~zappa/readings/ppopp13.pdf).  But I feel the benefit outweighs the cost in this case.
=> Simplify the control flow of chase-lev deque

CHANGELOG.md, README.md
The motivation of this release is just to get a few bug fixes and features out so that users don't wait for them forever. 
Crossbeam 0.2.x has several long-standing bugs (e.g. leaks and crashes in `MsQueue`). These have been fixed in the master branch, so I suggest we cut a new release. There were also some compatibility breaking changes, so I'm bumping to version 0.3.
The next steps in development will be rework of EBR and splitting Crossbeam up into multiple crates.
=> Bump to version 0.3

src/lib.rs
As reported in #167, `ScopedThreadBuilder` is returned from `Scope::builder()`, but it is not documented.  This solves this issue by exposing `ScopedThreadBuilder`.
Closes #167
=> Expose ScopedThreadBuilder

src/sync/arc_cell.rs, src/sync/ms_queue.rs, src/sync/seg_queue.rs
Mainly for `Default`s.
Just wonder why only `TreiberStack` implements `Default` :)
=> impl more std traits

CHANGELOG.md, README.md, src/lib.rs
This PR bumps to version 0.4!
Last year @aturon [called for a help for Crossbeam](https://internals.rust-lang.org/t/crossbeam-request-for-help/4933), and we Crossbeam developers gathered together to work on this wonderful project.  @stjepang stepped up to propose and lead a major overhaul, and as a result, we have successfully released a handful of sub-crates so far.  Now finally, we're ready to mark the end of the overhaul by releasing a new version of `crossbeam`: it is now an umbrella project of the Crossbeam sub-crates developed so far.  Let's celebrate it! 🎉  Thanks to all the contributors! 🙏
--
Updated README and CHANGELOG.
Closes #179 
Closes #181
=> Bump to 0.4

src/ms_queue.rs, src/seg_queue.rs
This will hopefully fix https://github.com/crossbeam-rs/crossbeam-epoch/issues/82
=> Use ManuallyDrop in queues

.travis.yml, README.md
The old Travis config is dated and doesn't even check for minimum Rust version. The old readme doesn't specify the minimum version nor the license.
This PR updates the Travis config and the readme.
=> Update Travis config and readme

crossbeam-epoch/src/internal.rs
It seems there was a bug in `Guard::repin()`: the newly pinned epoch was not marked as pinned.
=> Fix a bug in repin

.travis.yml, Cargo.toml, bors.toml
Using bors has multiple benefits:
* It streamlines PR approval process: just say "bors r+" and it will be tested & merged. We can also delegate permission to approve PRs, which means there will be less ping-ponging between reviewers.
* Once approved, the PR is automatically tested and merged into master. Note that it will be tested only once, while currently we test it twice (before the merge and after merge).
* It'll make it easier to reduce CI build times: https://github.com/rayon-rs/rayon/blob/8c05d2b8788dc64067d6e79ff3b3cfe90a5e249e/.travis.yml#L11-L13
See how Rayon uses bors-ng: https://github.com/rayon-rs/rayon/pull/451
Quick intro: https://bors.tech/documentation/getting-started/
=> Enable bors-ng

crossbeam-channel/examples/matching.rs
The code in Go is removed because it's already available by the provided links and the top section of comments got incredibly long.
Closes #228
=> Add a license for matching.go

crossbeam-deque/src/lib.rs, crossbeam-epoch/src/internal.rs
Thanks to @jeehoonkang for some early feedback.
=> Document some places where crossbeam tests the limits of the C++ memory model -- or crosses them

crossbeam-utils/src/lib.rs, crossbeam-utils/src/sync/mod.rs, crossbeam-utils/src/sync/parker.rs, crossbeam-utils/tests/parker.rs, src/lib.rs
This is just an extracted copy of the current implementation of `thread::park()` and `thread::unpark()`.
`Parker` is a low-level thread synchronization primitive useful for building others (like locks etc.). It would be useful in https://github.com/tokio-rs/tokio/pull/528 and might remove some cruft and unnecessary TLS access from `context.rs` in `crossbeam-channel`.
I've also added a fast-path check for `timeout == Duration::from_secs(0)`, which Tokio relies on.
An interesting peculiarity of `Parker` is that it's not split into `Parker` and `Unparker`, which means any thread can call `park()` at any time. However, if multiple threads call `park()` at the same time, expect deadlocks or panics - that is the user's problem. Splitting the primitive into an owned `Parker` and shared …
=> Add Parker for thread parking

crossbeam-skiplist/src/base.rs, crossbeam-skiplist/src/lib.rs, crossbeam-skiplist/src/map.rs, crossbeam-skiplist/src/set.rs, crossbeam-skiplist/tests/base.rs, crossbeam-skiplist/tests/map.rs
=> Use std::ops::Bound in crossbeam-skiplist

crossbeam-channel/src/select.rs
`SelectedOperation<'_>` doesn't really need to mutably borrow the whole `Select<'_>` - it's enough to borrow the senders and receivers.
=> Relax lifetimes on SelectedOperation

crossbeam-channel/src/channel.rs, crossbeam-channel/src/err.rs, crossbeam-channel/src/flavors/after.rs, crossbeam-channel/src/flavors/array.rs, crossbeam-channel/src/flavors/list.rs, crossbeam-channel/src/flavors/never.rs, crossbeam-channel/src/flavors/tick.rs, crossbeam-channel/src/flavors/zero.rs, crossbeam-channel/src/lib.rs, crossbeam-channel/src/select.rs, crossbeam-channel/src/waker.rs, crossbeam-channel/tests/after.rs, crossbeam-channel/tests/ready.rs, crossbeam-channel/tests/select.rs, crossbeam-channel/tests/select_macro.rs, crossbeam-channel/tests/tick.rs
This PR adds methods `Select::{try_ready,ready,ready_timeout}`, which wait on a set of operations until any one of them becomes ready. However, after that we're not obliged to "complete" the operation.
cc @Munksgaard @laumann This would help in resolving https://github.com/Munksgaard/session-types/issues/45
Closes #222.
If anyone thinks we should name these methods differently, speak up! :)
=> Wait on a set of operations without committing to any

crossbeam-channel/src/err.rs
Add methods like `is_disconnected()`, `is_full()`, and `is_empty()` to error types returned by channel operations.
=> Add additional is_* methods to error types

Cargo.toml, src/lib.rs, tests/subcrates.rs
Two changes:
* Render subcrate docs properly.
* Specify minor versions of crossbeam subcrates (same as in [Tokio](https://github.com/tokio-rs/tokio/blob/master/Cargo.toml)).
=> Use inline docs and specify subcrate minor versions

.travis.yml, crossbeam-skiplist/README.md, crossbeam-skiplist/src/base.rs, crossbeam-skiplist/src/map.rs, crossbeam-skiplist/src/set.rs, crossbeam-skiplist/tests/base.rs, crossbeam-skiplist/tests/map.rs
This lets use use `RangeBounds` for `ref_iter()` and `ref_range()`.
Signatures of `iter()` and `range()` are unchanged, though.
=> skiplist: Simplify RefIter and RefRange

crossbeam-epoch/src/guard.rs
While `Guard::clone()` is a nice convenience, it's not really a method we *need*.
By removing the clone impl, we enable some kinds of API. For example, a data structure might want to return a `Guard` to the user and then retrieve it back knowing it has never been cloned.
@Amanieu needs to forbid `Guard::clone()` in a certain use case. I don't remember the exact details, so perhaps he could comment what it is about.
=> Remove Clone for Guard

crossbeam-skiplist/src/base.rs
This addresses #246 by removing the allocation hack that was in place before.
Signed-off-by: Toby Lawrence <toby@nuclearfurnace.com>
=> skiplist: switch to alloc API

crossbeam-skiplist/src/base.rs
This addresses comments in #268 about handling allocation errors correctly.
/cc @stjepang @SimonSapin 
Signed-off-by: Toby Lawrence <toby@nuclearfurnace.com>
=> skiplist: properly handle alloc error

crossbeam-epoch/src/atomic.rs
It is possible that the user would like to have one thread to be able to
update the value of the object pointed by Atomic. For that, they will
need to have a mutable refernce towards that object.
This is an unsafe function because there is no guarantee that there are
more threads attempting to read/write from/to the actual object in the
same time.
In order to proivde safety the user must be able to know that there are
no concurrent accesses towards the object itself and/or use
crossbeam_utils::atomic::AtomicCell to provide the needed guarantees.
=> crossbeam-epoch: Add Shared::deref_mut()

Cargo.toml, src/lib.rs, src/sharded_lock.rs
This removes the dependency on `num_cpus`. If we also remove dependency on `parking_lot`, then `ShardedLock` can be moved into `crossbeam-utils`.
The `num_shards` arguments is somewhat reminiscent of `concurrencyLevel` in [this](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#ConcurrentHashMap-int-float-int-) `ConcurrentHashMap` constructor.
=> Add num_shards argument to ShardedLock::new

crossbeam-channel/Cargo.toml, crossbeam-channel/src/context.rs, crossbeam-channel/src/flavors/list.rs, crossbeam-channel/src/lib.rs, crossbeam-channel/tests/ready.rs
Use a different queue for unbounded channels.
This gives us:
* Performance improvements (see benchmarks below).
* Lower memory consumption (memory reclamation is not deferred, it's *eager*).
* Fewer dependencies (no more `crossbeam-epoch`).
Before:
```
unbounded_mpmc            Rust crossbeam-channel   0.392 sec
unbounded_mpsc            Rust crossbeam-channel   0.373 sec
unbounded_select_both     Rust crossbeam-channel   0.536 sec
unbounded_select_rx       Rust crossbeam-channel   0.589 sec
unbounded_seq             Rust crossbeam-channel   0.462 sec
unbounded_spsc            Rust crossbeam-channel   0.235 sec
```
After:
```
unbounded_mpmc            Rust crossbeam-channel   0.266 sec
unbounded_mpsc            Rust crossbeam-channel   0.250 sec
unbounded_select_both     Rust …
```
=> Optimize unbounded channels

crossbeam-channel/src/channel.rs, crossbeam-channel/src/counter.rs, crossbeam-channel/src/flavors/after.rs, crossbeam-channel/src/flavors/never.rs, crossbeam-channel/src/flavors/tick.rs, crossbeam-channel/src/lib.rs, crossbeam-channel/tests/select.rs, crossbeam-channel/tests/select_macro.rs
This changes the size of `Receiver`s from 32 bytes to 16 bytes and the size of `Sender` from 8 bytes to 16 bytes.
The amount of reference counting going on is reduced too, which makes channel construction and destruction slightly faster.
=> Reduce the size of Receiver

README.md, crossbeam-utils/src/sync/mod.rs, crossbeam-utils/src/thread.rs, src/lib.rs
The root `crossbeam` module had outdated documentation and broken links. This PR moves the contents of the readme into the root module and expands some docs for `crossbeam-utils`.
=> Documentation improvements

.travis.yml, README.md, crossbeam-channel/src/select.rs, crossbeam-channel/tests/ready.rs, crossbeam-deque/README.md, crossbeam-deque/src/lib.rs, crossbeam-deque/tests/fifo.rs, crossbeam-deque/tests/injector.rs, crossbeam-deque/tests/lifo.rs, crossbeam-deque/tests/steal.rs, tests/subcrates.rs
This PR introduces a big set of changes:
* `Injector<T>` is introduced, which is a MPMC FIFO queue. Every task scheduler (Rayon, Tokio, Go, TBB, Cilk, you name it) has an "injector" queue, through which tasks are spawned onto the thread pool. This is a special queue supports it batched steal operations.
* `fifo()` and `lifo()` constructors are changed to `Worker::new_fifo()` and `Worker::new_lifo()`. Stealers are created using `Worker::stealer()`.
* `steal_many()` is renamed to `steal_batch_and_pop()`.
* There's a new batched steal method named `steal_batch()`. It moves only a batch of tasks into another `Worker` - it doesn't return an additional task.
* `Steal::Data` is renamed to `Steal::Success` because `steal_batch()` returns `Steal<()>`, which means the success case doesn't have …
=> deque: add MPMC queue and new batched steal methods

crossbeam-channel/Cargo.toml, crossbeam-channel/src/flavors/zero.rs, crossbeam-channel/src/lib.rs, crossbeam-channel/src/utils.rs, crossbeam-channel/src/waker.rs, crossbeam-channel/tests/golang.rs
`parking_lot` is a big dependency, which is discouraging library writers from using `crossbeam-channel`. I am therefore removing it.
Mutexes are replaced with a simple spinlock that yields threads on contention. That should be ok since all critical sections are small anyway. Benchmarks look good (see below).
Previous dependency tree:
```
crossbeam-channel v0.3.6 (/home/stjepan/work/crossbeam/crossbeam-channel)
├── crossbeam-utils v0.6.3 (/home/stjepan/work/crossbeam/crossbeam-utils)
│   └── cfg-if v0.1.6
├── parking_lot v0.7.1
│   ├── lock_api v0.1.5
│   │   ├── owning_ref v0.4.0
│   │   │   └── stable_deref_trait v1.1.1
│   │   └── scopeguard v0.3.3
│   └── parking_lot_core v0.4.0
│       ├── libc v0.2.47
│       ├── rand v0.6.4
│       │   ├── libc v0.2.47 (*)
│       │   ├── …
```
=> channel: remove parking_lot dependency

crossbeam-utils/src/atomic/atomic_cell.rs
The lack of larger atomics on thumbv7m-none-eabi (and I'm guessing
similar embedded platforms as well) was causing build errors.
=> Use `target_has_atomic` in `impl_arithmethic`

README.md, crossbeam-channel/src/context.rs, crossbeam-channel/src/flavors/array.rs, crossbeam-channel/src/flavors/list.rs, crossbeam-channel/src/flavors/zero.rs, crossbeam-channel/src/select.rs, crossbeam-channel/src/utils.rs, crossbeam-deque/src/lib.rs, crossbeam-utils/README.md, crossbeam-utils/benches/atomic_cell.rs, crossbeam-utils/src/atomic/atomic_cell.rs, crossbeam-utils/src/backoff.rs, crossbeam-utils/src/lib.rs, src/lib.rs, src/queue/array_queue.rs, src/queue/seg_queue.rs
This is one of those simple tools like `CachePadded` that comes up so often it is useful to have it in the library, despite being easy to implement. `Backoff` calls `spin_loop_hint()` and `yield_now()` with good default settings that work well across a wide spectrum of workloads.
Currently, `crossbeam-channel`, `crossbeam-deque`, and `SegQueue` have their own `Backoff`s so this PR just removes duplication.
There's even a place in Tokio where this might be useful as we previously struggled with tuning backoff manually and got it wrong: https://github.com/tokio-rs/tokio/pull/534
=> utils: add Backoff for exponential backoff

crossbeam-epoch/src/atomic.rs, crossbeam-epoch/src/collector.rs, crossbeam-epoch/src/internal.rs, crossbeam-skiplist/tests/base.rs
Removes some compilation warnings because `ATOMIC_USIZE_INIT` is deprecated.
=> Remove ATOMIC_USIZE_INIT

.travis.yml, Cargo.toml, ci/crossbeam-queue.sh, crossbeam-channel/benchmarks/segqueue.rs, crossbeam-channel/src/channel.rs, crossbeam-queue/Cargo.toml, crossbeam-queue/LICENSE-APACHE, crossbeam-queue/LICENSE-MIT, crossbeam-queue/LICENSE-THIRD-PARTY, crossbeam-queue/README.md, crossbeam-queue/src/array_queue.rs, crossbeam-queue/src/err.rs, crossbeam-queue/src/lib.rs, crossbeam-queue/src/seg_queue.rs, crossbeam-queue/tests/array_queue.rs, crossbeam-queue/tests/seg_queue.rs, src/lib.rs, tests/subcrates.rs
This PR moves `ArrayQueue` and `SegQueue` into a new crate `crossbeam-queue`.
We need queues in a crate that doesn't pull all other Crossbeam crates as a dependency. In particular, Tokio wants to use MPMC queues but cares a lot about keeping its dependency tree as small as possible. See #292 for more information.
Since we already have the `crossbeam::queue` module, and this simply extracts it into `crossbeam-queue`, and there's a real need for moving queues out of `crossbeam`, I believe the introduction of a new crate should be uncontroversial.
I'll leave this PR open for a few days and merge if there are no objections. If anyone feels this might be a wrong decision, please speak up!
Closes #292
=> Move queues into crossbeam-queue

crossbeam-channel/tests/mpsc.rs
A lot of tests created threads but never waited (joined) on them. As a
result if one of those threads panicked they test still passed and the
test runner exits with a success exit code.
Updates #321.
=> Join all threads created in tests

crossbeam-channel/tests/thread_locals.rs
Updates #321.
As per @stjepang suggestion in https://github.com/crossbeam-rs/crossbeam/issues/321#issuecomment-461024423.
=> Skip use_while_exiting test on macOS

crossbeam-utils/src/cache_padded.rs
Motivation: https://www.reddit.com/r/rust/comments/akzas0/lockfree_rust_crossbeam_in_2019/efa26r1/
=> CachePadded: use 128-byte alignment on x86-64

crossbeam-utils/src/atomic/atomic_cell.rs
This is an essential step in solving #315 - there is no way to make `AtomicCell::get_mut()` sound, unfortunately. Let's deprecate it and remove in the next release.
=> Deprecate AtomicCell::get_mut

crossbeam-skiplist/src/base.rs, crossbeam-skiplist/src/lib.rs, crossbeam-skiplist/src/map.rs
This PR fixes #273. ~in the case where you are using `clear`. The memory leak still persists when you use `Entry::remove()`~. EDIT: both cases are fixed with https://github.com/crossbeam-rs/crossbeam/commit/a6de0ca23b5364d2acc876f6e3d74cb8ab4d7b4a.
I find that when creating a new `Entry`, a reference counter to the node gets incremented, but the counter won't get decremented when `Entry` gets dropped. This could be why garbage were not collected, though I am not entirely sure if it is right. Looking forward to see reviews from the crossbeam maintainers.
Thank you for creating great piece of code and documentation. It was very fun to read both of them.
=> Release `RefEntry` when dropping `Entry`

crossbeam-queue/src/array_queue.rs
This `+ 1` is what distinguishes already fully written slot from a free or partially written slot
=> fix comment

.travis.yml, Cargo.toml, ci/dependencies.sh, crossbeam-channel/Cargo.toml, crossbeam-channel/benchmarks/Cargo.toml, crossbeam-epoch/Cargo.toml, crossbeam-skiplist/Cargo.toml, crossbeam-utils/Cargo.toml
Related: https://github.com/crossbeam-rs/crossbeam/issues/312, https://github.com/rust-lang/cargo/issues/5657
=> Add minimal versions check to travis

README.md, crossbeam-epoch/README.md, crossbeam-skiplist/README.md, crossbeam-utils/README.md
[rendered](https://github.com/yoshuawuyts/crossbeam/blob/e62a39f32e9582b9ff9f0114572eeb173710112c/README.md)
This patch changes the asterisk / double asterisk notation in the READMEs to a long-form variant.
I was reading the README, and it took me a bit to figure out what the asterisks mean. I couldn't figure it out on first glance, so I scrolled down to the bottom of the page, which didn't yield results. Only after careful searching did I find what it meant.
This patch would solve most of the confusion I ran into by just placing the meaning right next to the text, similar to dietary restrictions in a restaurant menu. I feel this would've saved me a bit of searching, and might for others too.
Hope this is helpful; sorry if it's trivial or not really useful. Thanks for your time! …
=> long-form superscript notation in readmes

crossbeam-channel/Cargo.toml, crossbeam-channel/src/lib.rs, crossbeam-channel/src/select.rs
This doesn't seem to affect benchmarks.
=> crossbeam-channel: Remove dependency on smallvec

crossbeam-channel/src/flavors/tick.rs, crossbeam-channel/tests/array.rs, crossbeam-channel/tests/list.rs, crossbeam-channel/tests/ready.rs, crossbeam-channel/tests/select.rs, crossbeam-channel/tests/select_macro.rs, crossbeam-channel/tests/zero.rs
The CI says (https://travis-ci.org/crossbeam-rs/crossbeam/jobs/523343513#L485):
```
error: variable does not need to be mutable
--> crossbeam-channel/src/flavors/tick.rs:63:21
|
63 |                 let mut delivery_time = self.delivery_time.load();
|                     ----^^^^^^^^^^^^^
|                     |
|                     help: remove this `mut`
|
= note: `-D unused-mut` implied by `-D warnings`
error: aborting due to previous error
```
(Not sure why warning is issued as an error.)  Fixing this error.
=> Fix CI errors

.travis.yml, crossbeam-channel/README.md, crossbeam-epoch/README.md, crossbeam-queue/README.md, crossbeam-utils/README.md, crossbeam-utils/src/atomic/atomic_cell.rs
=> Add AtomicCell member functions

crossbeam-epoch/CHANGELOG.md, crossbeam-epoch/src/atomic.rs
To mimic Shared::into_owned.
Closes #369
=> epoch: Add Atomic::into_owned

.travis.yml, crossbeam-channel/README.md, crossbeam-epoch/README.md, crossbeam-queue/README.md, crossbeam-utils/README.md, crossbeam-utils/src/atomic/atomic_cell.rs
Closes #365 
Remaining question: should we commit to support the minimum supported Rust version of Rayon?
=> Support Rust 1.26

crossbeam-utils/src/atomic/atomic_cell.rs
PR #332 deprecated after the discussion of issue #315, but it is a
measure not yet necessary to take. Revert the deprecation and wait
for us to reach a consensus.
=> De-deprecate AtomicCell::get_mut

crossbeam-epoch/src/internal.rs, crossbeam-epoch/src/sync/list.rs
Use `Owned` instead of `Box` when `Owned`'s implementation details are not neccessary
=> Remove unnecessary mention of Box

crossbeam-channel/Cargo.toml, crossbeam-queue/Cargo.toml
The BSD License is mentioned in the code, but not visible in the metadata. I want to use this crate at work and fixing the metadata would help.
=> add BSD license to crossbeam-queue metadata

crossbeam-epoch/src/internal.rs, crossbeam-epoch/src/sync/list.rs
When an entry is unlinked from list, the current implementation calls `defer_unchecked()` the invocation of the entry's finalizer.  This PR proposes to fix it in such a way that when an entry is unlinked from list, the finalizer is immediately called.
Here is an example why the current implementation is wrong, and this PR fixes it.  Suppose an element is in two (intrusive) linked lists, and their corresponding two finalizers (1) check if the element is unlinked from both lists, and if so, (2) defer the deallocation of the element.  The current implementation cannot express this idea because the invocation of the entry's finalizer is deferred.  On the other hand, this PR can express this idea directly.
=> Fix list's finalize API

crossbeam-utils/src/atomic/atomic_cell.rs
This should be correct since (I assume) `AtomicCell` never panics in a method and
will therefore always be correct (under any unrelated panics)
=> feat: impl {Ref,}UnwindSafe for AtomicCell

crossbeam-epoch/Cargo.toml, crossbeam-epoch/src/internal.rs, crossbeam-epoch/src/lib.rs
`ArrayVec` is used in just one place, and even there crossbeam uses a small part of its API surface. This PR replaces ArrayVec with 100% safe code using a plain old array and ditches the ArrayVec dependency altogether.
This removes 170 unsafe expressions from the dependency tree according to [cargo-geiger](https://github.com/anderejd/cargo-geiger). With less unsafe code to worry about there's less chance of memory safety bugs, and safety/security audits will be cheaper and easier to perform.
An unfortunate casualty of this change is `#[derive(Debug)]` on internal structures because there is no Debug implementation for `[T; 64]` - these impls are only generated up to length of 32. It will be possible to re-enable it once const generics are stabilized. For now they're implemented manually. …
=> Remove ArrayVec dependency

crossbeam-epoch/src/internal.rs
Addresses [this comment](https://github.com/crossbeam-rs/crossbeam/pull/414#discussion_r328208426) that I didn't get a chance to act upon before merging #414. 
This way bounds checks should be performed only once. However, this does not measurably impact benchmarks.
=> Do not perform superfluous bounds checks on dropping crossbeam-epoch::Bag

CHANGELOG.md, Cargo.toml, README.md, crossbeam-channel/CHANGELOG.md, crossbeam-channel/Cargo.toml, crossbeam-channel/README.md, crossbeam-deque/CHANGELOG.md, crossbeam-deque/Cargo.toml, crossbeam-deque/README.md, crossbeam-epoch/CHANGELOG.md, crossbeam-epoch/Cargo.toml, crossbeam-epoch/README.md, crossbeam-queue/CHANGELOG.md, crossbeam-queue/Cargo.toml, crossbeam-queue/README.md, crossbeam-skiplist/Cargo.toml, crossbeam-skiplist/README.md, crossbeam-utils/CHANGELOG.md, crossbeam-utils/Cargo.toml, crossbeam-utils/README.md
This updates version numbers and changelogs.
- crossbeam 0.7.3
- crossbeam-channel 0.4.0
- crossbeam-deque 0.7.2
- crossbeam-epoch 0.8.0
- crossbeam-queue 0.2.0
- crossbeam-utils 0.7.0
cc #435 
cc #443 
cc #446
=> Prepare for the next release

crossbeam-epoch/src/lib.rs
The docs tried to refer to a top-level 'defer' function; instead link to
Guard::defer.
=> fix broken doc link

crossbeam-epoch/src/default.rs, crossbeam-epoch/src/internal.rs, crossbeam-skiplist/src/map.rs, crossbeam-skiplist/src/set.rs, crossbeam-utils/src/atomic/seq_lock_wide.rs, crossbeam-utils/src/sync/mod.rs, crossbeam-utils/src/sync/parker.rs, crossbeam-utils/src/sync/sharded_lock.rs, crossbeam-utils/src/sync/wait_group.rs
This fix build failure in #449 and #448
It seems old rustfmt did not properly format the module in the macro.
=> Format with rustfmt

crossbeam-utils/build.rs, crossbeam-utils/src/atomic/atomic_cell.rs, crossbeam-utils/tests/atomic_cell.rs
=> Make AtomicCell lockfree for u8, u16, u32, u64 sized values.

crossbeam-channel/src/flavors/tick.rs
Due to the way `recv()` was implemented for the tick flavor, there was always some unintended drift because we had a loop that sleeps until the next tick and then checks if the tick happened.
This PR simplifies the `recv()` method and fixes the drift. Now we try to receive the message first and *then* sleep until the next tick.
Fixes #406
=> Simplify tick channel

crossbeam-deque/src/lib.rs, crossbeam-epoch/src/default.rs, crossbeam-epoch/src/internal.rs, crossbeam-skiplist/src/map.rs, crossbeam-skiplist/src/set.rs, crossbeam-utils/src/atomic/seq_lock_wide.rs, crossbeam-utils/src/sync/mod.rs, crossbeam-utils/src/sync/parker.rs, crossbeam-utils/src/sync/sharded_lock.rs, crossbeam-utils/src/sync/wait_group.rs
This PR checks whether the source and destination deque are the same when stealing tasks. If so, we return from the function early.
=> Don't steal from the same deque

crossbeam-epoch/src/sync/list.rs
In list iteration, even though the CAS to delete a node fails, the iteration may be able to proceed by re-reading the predecessor's next pointer.  A more precise explanation is in the comments.
=> Reduce stall in list iteration

crossbeam-epoch/src/sync/queue.rs
`pop()` must completely unlink the popped node from the shared memory before it calls `defer_destroy()` to prevent use-after-free. This implementation is based on the variation by Doherty et al. where the `head == tail` check is done after a successful CAS, which can be slightly more efficient than the original MSQueue.
closes #238
=> fix use-after-free in crossbeam-epoch/sync/queue

crossbeam-channel/Cargo.toml, crossbeam-channel/src/flavors/array.rs, crossbeam-channel/src/flavors/list.rs, crossbeam-channel/src/lib.rs, crossbeam-deque/Cargo.toml, crossbeam-deque/src/lib.rs, crossbeam-epoch/Cargo.toml, crossbeam-epoch/src/deferred.rs, crossbeam-epoch/src/lib.rs, crossbeam-epoch/src/sync/queue.rs, crossbeam-queue/Cargo.toml, crossbeam-queue/src/array_queue.rs, crossbeam-queue/src/lib.rs, crossbeam-queue/src/seg_queue.rs
Several libs in crossbeam contain unsound code (eg. `Block::new`). This PR fixes them and requires a MSRV upgrade to 1.36.
=> Fix unsoundness issues (mem::zeroed / ManuallyDrop -> MaybeUninit)

crossbeam-epoch/examples/treiber_stack.rs
I think it is correct to use relaxed ordering, since:
1. pop function has no data to publish to other thread.
2. all write operations on `TreiberStack.head` is atomic read-modify-write, so will be part of the `release sequence` headed by the release operation in `push` function, according to the [cpp ref](https://en.cppreference.com/w/cpp/atomic/memory_order).
=> relax memory ordering of treiber stack

Cargo.toml, crossbeam-queue/Cargo.toml, crossbeam-queue/src/lib.rs, src/lib.rs
The crossbeam_queue crate is no_std compatible since #455.
=> Make the `queue` module available on no_std + alloc

crossbeam-queue/src/err.rs
Currenly, `PushError` and `PopError` do not implement `std::error::Error` even when `std` feature is activated :(
=> Fix `features` typo in ArrayQueue's error types (crossbeam-queue)

crossbeam-channel/src/flavors/array.rs, crossbeam-queue/src/array_queue.rs
As far as I can tell, `ArrayQueue::new()` would previously create temporary references
to uninitialized data, which is undefined behavior. The stamps for the `Slot` buffer were initialized like so:
```rust
// Initialize stamps in the slots.
for i in 0..cap {
unsafe {
// Set the stamp to `{ lap: 0, index: i }`.
let slot = buffer.add(i);
ptr::write(&mut (*slot).stamp, AtomicUsize::new(i));
}
}
```
As I see it, the code above creates a temporary reference to the uninitialized `Slot`s on the call to `ptr::write()`, equivalent to the following:
```rust
for i in 0..cap {
unsafe {
// Undefined behavior: reference to uninitialized memory
let slot: &mut Slot<T> = &mut *buffer.add(i);
// ... 
}
}
```
The problem was fixed by creating the `slots` vector using `Iterator::collect()`. This has the …
=> Fix potential undefined behavior in ArrayQueue initialization

crossbeam-channel/src/waker.rs
Fix for #451 
This does not seem to have a noticeable influence on the benchmarks
=> channel: call notify only from one thread

crossbeam-channel/tests/golang.rs
The original test has:
https://github.com/golang/go/blob/03bb3e9ad13ef49afbed7e422d21ef6eb00389c1/src/runtime/chan_test.go#L105-L108
Notably `done <- v == 0 && ok == false`, which in Rust ought to be `done.send(v.is_none())`.
=> Fix golang test (chan_test)

crossbeam-utils/src/cache_padded.rs
"Big" cores on ARM's bigLITTLE architecture do have 128 byte cache line according to this article
https://www.mono-project.com/news/2016/09/12/arm64-icache/
(it is also sourced in the code)
This has not been benchmarked (I just do not have the hardware to do so)
=> CachePadded: double cache size on aarch64

crossbeam-channel/tests/ready.rs
=> Relax racy fairness test

crossbeam-utils/src/thread.rs, crossbeam-utils/tests/thread.rs
Resolves #197
I implemented `into_pthread_t()`/`into_raw_handle()` methods by calling the `as` variants, as I'm not sure it would be sound to consume the join handle, since there would then be no guarantee the thread is joined before the end of the scope.
=> Implement OS extension traits for ScopedJoinHandle

crossbeam-utils/src/atomic/seq_lock.rs
This is minor, but I noticed it on a read of the code. `abort()` would
write back the old stamp, but would then immediately drop `self`,
which would bump the stamp anyways.
I included a test; SeqLock isn't exported, so it wasn't possible to
add this to the integratio suite so I added it directly in the file.
=> SeqLock: Aborted writes should not update the stamp.

crossbeam-epoch/src/internal.rs, crossbeam-skiplist/tests/base.rs, crossbeam-utils/src/cache_padded.rs
This patch implements the fix discussed in https://github.com/crossbeam-rs/crossbeam/issues/238#issuecomment-525795655. 
* tag the Bag with the local epoch E
* free at E+3
=> Require three epoch advancements for deallocation 

crossbeam-channel/src/select_macro.rs, crossbeam-channel/tests/select_macro.rs
=> Remove #[allow(unsafe_code)] from select! macro

crossbeam-utils/src/atomic/atomic_cell.rs, crossbeam-utils/src/backoff.rs
Remove deprecated `AtomicCell::get_mut` and `Backoff::is_complete`
This is a breaking change proposed in #503.
=> Remove deprecated methods

crossbeam-channel/src/err.rs, crossbeam-queue/src/err.rs
=> Remove deprecated Error::{description, cause} impls

crossbeam-epoch/src/internal.rs, crossbeam-skiplist/tests/base.rs, crossbeam-utils/src/cache_padded.rs
Reverts crossbeam-rs/crossbeam#416
I'm suspecting may this PR causes #514.  Here's a revert PR, and I'd like to test if SIGSEGV is gone after reverting the PR...
=> Revert "Require three epoch advancements for deallocation "

crossbeam-channel/src/channel.rs, crossbeam-channel/src/lib.rs, crossbeam-channel/src/select.rs, crossbeam-channel/src/select_macro.rs, crossbeam-deque/src/deque.rs, crossbeam-deque/src/lib.rs, crossbeam-epoch/src/atomic.rs, crossbeam-epoch/src/guard.rs, crossbeam-epoch/src/lib.rs, crossbeam-epoch/src/sync/queue.rs, crossbeam-queue/src/array_queue.rs, crossbeam-queue/src/lib.rs, crossbeam-queue/src/seg_queue.rs, crossbeam-skiplist/src/lib.rs, crossbeam-utils/src/atomic/atomic_cell.rs, crossbeam-utils/src/lib.rs, crossbeam-utils/src/sync/parker.rs, crossbeam-utils/src/thread.rs, src/lib.rs
There are some unused imports/`mut`s.
Refs: rust-lang/futures-rs#1672, tokio-rs/tokio#1539
=> Deny warnings for doc tests

crossbeam-epoch/src/atomic.rs, crossbeam-epoch/src/collector.rs, crossbeam-epoch/src/internal.rs, crossbeam-epoch/src/lib.rs, crossbeam-epoch/src/sync/list.rs, crossbeam-epoch/src/sync/queue.rs
It supersedes #209 for supporting dynamically sized types (DST) in Crossbeam.  It's much cleaner and less intrusive than the previous attempts in that it doesn't introduce another `Atomic` type.  `Atomic<T>` is still there without significant changes.
The key idea is (1) instead of requiring the condition on `T: Sized`, (2) requiring `T: Pointable` that means an object of type `T` can be pointed to by a single word.  For instance, `Atomic` becomes: `pub struct Atomic<T: ?Sized + Pointable> { ... }`.
It is breaking the backward compatibility in that it ~~(1) increases the minimum required Rust version to 1.36 (for `MaybeUninit`) and (2)~~ now `const fn Atomic::null()` is Nightly only.
=> Support dynamically sized types

crossbeam-utils/src/thread.rs, crossbeam-utils/tests/thread.rs
Currently we convert the FnOnce closure to a FnMut closure. This is not
needed and there is no comment explaining why this is done. I suspect
this might have been required originally because the api or compiler was
different.
=> Remove obsolete FnMut conversion

.github/workflows/ci.yml, ci/check-features.sh, ci/crossbeam-channel.sh, ci/crossbeam-epoch.sh, ci/crossbeam-queue.sh, ci/crossbeam-skiplist.sh, ci/crossbeam-utils.sh, ci/crossbeam.sh, crossbeam-queue/Cargo.toml
This adds a check for all feature combinations to CI.
*This originally suggested by @jonhoo in https://github.com/crossbeam-rs/crossbeam/pull/504#issuecomment-631454134.*
=> Check all feature combinations works properly on CI

crossbeam-epoch/src/atomic.rs, crossbeam-utils/src/thread.rs
This allows you to test if the code fails with the expected error.
=> Mark some ignored doc tests as compile_fail

crossbeam-epoch/Cargo.toml, crossbeam-epoch/src/atomic.rs, crossbeam-utils/Cargo.toml, crossbeam-utils/src/atomic/atomic_cell.rs, crossbeam-utils/tests/atomic_cell.rs
=> Make AtomicCell::is_lock_free const function at 1.46+

crossbeam-utils/src/atomic/atomic_cell.rs
std atomic types also have similar `From` impls: e.g., [`AtomicBool`](https://doc.rust-lang.org/nightly/std/sync/atomic/struct.AtomicBool.html#impl-From%3Cbool%3E), [`AtomicUsize`](https://doc.rust-lang.org/nightly/std/sync/atomic/struct.AtomicUsize.html#impl-From%3Cusize%3E)
=> impl From<T> for AtomicCell<T>

crossbeam-epoch/src/internal.rs
Set `MAX_OBJECTS` to 62, and make the size of `Local` to 2040 bytes.
Closes #551
=> Make Local less than 2048 bytes

crossbeam-channel/CHANGELOG.md, crossbeam-channel/Cargo.toml
See https://github.com/crossbeam-rs/crossbeam/pull/537#issuecomment-687755200 for details.
(The `v0.7` branch itself is based on the commits we made when I released crossbeam-queue v0.2.3 in https://github.com/crossbeam-rs/crossbeam/issues/523#issuecomment-642347864.)
Backports:
* #537 
* https://github.com/crossbeam-rs/crossbeam/commit/5a68889cbc490f71fce5e615572e586cf15668a6
=> v0.7: Bump crossbeam-channel to v0.4.4

ci/crossbeam-channel.sh, ci/crossbeam-deque.sh, ci/crossbeam-epoch.sh, ci/crossbeam-queue.sh, ci/crossbeam-skiplist.sh, ci/crossbeam-utils.sh, ci/crossbeam.sh, crossbeam-channel/src/channel.rs, crossbeam-channel/src/err.rs, crossbeam-channel/src/lib.rs, crossbeam-channel/src/select.rs, crossbeam-channel/src/select_macro.rs, crossbeam-deque/src/lib.rs, crossbeam-epoch/src/atomic.rs, crossbeam-epoch/src/guard.rs, crossbeam-epoch/src/lib.rs, crossbeam-queue/src/array_queue.rs, crossbeam-queue/src/lib.rs, crossbeam-queue/src/seg_queue.rs, crossbeam-utils/src/lib.rs, crossbeam-utils/src/sync/mod.rs, crossbeam-utils/src/sync/sharded_lock.rs, src/lib.rs
Switch to use [intra-doc links](https://github.com/rust-lang/rfcs/pull/1946) in all crates. Previously there was a big bug on cross crate re-exports (https://github.com/rust-lang/rust/issues/65983), but it has been fixed, so we can use this in crossbeam.
This also adds checks of the docs to CI.
=> Use intra-doc links

crossbeam-channel/src/channel.rs, crossbeam-channel/src/flavors/after.rs, crossbeam-channel/src/flavors/at.rs, crossbeam-channel/src/flavors/mod.rs, crossbeam-channel/src/lib.rs, crossbeam-channel/src/select.rs
Added:
- `Receiver::recv_deadline`
- `Sender::send_deadline`
- `channel::at` (the deadline version of `channel::after`)
- `Select::select_deadline`
- `Select::ready_deadline`
Added associated docs & doctests for these, but in general they share implementations with the existing `timeout` versions, so I didn't add additional unit tests.
Didn't add a deadline version of the select macro for now, since it wasn't clear what the syntax would be or if it's really necessary (since deadline versions of things will be more for low/medium-level abstractions built on top of crossbeam, which would want to minimize abstraction).
Didn't add Parker::park_deadline, since that would have involved a heavier refactor of the `Parker` implementation (probably removing the possibility of a spurious wakeup). …
=> Added "deadline" versions of the various "timeout" entry points in crossbeam channel

ci/dependencies.sh
`cargo tree` subcommand is available by default since Rust 1.44.
=> ci: Do not install cargo-tree from crates.io

crossbeam-channel/tests/golang.rs
A port of select2.go to Rust. Select2 tests for excess memory usage by the select statement. The original go test uses memstats.alloc within the "runtime" package  to determine the net number of bytes allocated on the heap. I used a wrapper around alloc::System to achieve a similar behavior for the Rust port.
I also added make_unbounded() to initialize unbounded channels the go way.
#201
=> Port select2.go test to Rust

crossbeam-epoch/src/collector.rs
Reportrd by Miri in #578 ([log](https://github.com/crossbeam-rs/crossbeam/runs/1232029543?check_suite_focus=true))
https://github.com/crossbeam-rs/crossbeam/blob/e08b21cc086fc42af0e9927a68bc3120bee87af5/crossbeam-epoch/src/collector.rs#L378-L388
`ptr` is a pointer to `Vec<i32>`, but deallocated as `Vec<u8>`.
=> Fix UB in destroy_array test

crossbeam-epoch/src/guard.rs
Noticed that this hack isn't necessary (anymore?); originally had a newtype over `Guard` that I implemented `Sync` for, and then I realized that a `static mut` works as well.
=> Get rid of the hack for epoch::unprotected

crossbeam-utils/Cargo.toml, crossbeam-utils/src/atomic/atomic_cell.rs, crossbeam-utils/tests/atomic_cell.rs
`if` expression can only be used in const fn since Rust 1.46, so const `is_lock_free` was require Rust 1.46 (context: #531, #546).
However, when we replace uses of `if` expression with `|` and `&` operators, it seems `is_lock_free` can be used as const fn even in Rust 1.36.
r? @jeehoonkang or @Vtec234
=> Make AtomicCell::is_lock_free always const fn

crossbeam-utils/build.rs
`autocfg::new()` panics if unable to determine rustc version. However, that should not be a fatal error for the library.
=> Do not fail to compile if autocfg unable to determine rustc version

crossbeam-epoch/src/internal.rs
@decathorpe Thank you for reporting this.  It's also kinda hotfix.  As @taiki-e said, we really need CI for i686 and other 32-bit architectures... (#598).
r? @taiki-e
=> Relaxed size constrait of Local (closes #597)

crossbeam-utils/src/sync/mod.rs, crossbeam-utils/src/sync/parker.rs, crossbeam-utils/tests/parker.rs
- No longer a possibility for a spurious wake (previously possible if using a timeout), and removed references to spurious wake in the documentation.
- Implementation updates to `park`: now deadline based, and unified the code paths between timeout and no-timeout versions
- **Breaking Change** `park_timeout` and `park_deadline` now report the reason for their return (timeout or `unpark`) in an enum.
If you'd rather not have this breaking change, I'm happy to revert that side of it and just focus on the spurious awakening prevention stuff.
Fixes #482
=> Updates to `Parker`

crossbeam-epoch/Cargo.toml, crossbeam-epoch/src/atomic.rs
This dependency is only actually used for the nightly feature.
=> Make const_fn crate optional dependency

.github/workflows/ci.yml
Pin major version because the master branch of GHA actions can make
breaking changes.
=> Pin versions of GHA actions

crossbeam-channel/src/flavors/list.rs, crossbeam-epoch/src/epoch.rs, crossbeam-epoch/src/internal.rs, crossbeam-queue/src/seg_queue.rs, crossbeam-utils/src/backoff.rs
`compare_and_swap` is deprecated in 1.50. (https://github.com/rust-lang/rust/pull/79261)
This patch replaces the uses of `compare_and_swap` with `compare_exchange`.
See also the document about `compare_and_swap` -> `compare_exchange(_weak)` migration: https://doc.rust-lang.org/nightly/core/sync/atomic/struct.AtomicUsize.html#migrating-to-compare_exchange-and-compare_exchange_weak
=> Replace deprecated compare_and_swap with compare_exchange

crossbeam-utils/benches/atomic_cell.rs, crossbeam-utils/src/atomic/atomic_cell.rs
The standard library deprecated `compare_and_swap` in favor of `compare_exchange(_weak)` in 1.50. (rust-lang/rust#79261)
Given why std `compare_and_swap` was deprecated, it probably makes sense to do the same with `AtomicCell::compare_and_swap`.
Closes #618
=> Deprecate AtomicCell::compare_and_swap

.github/workflows/ci.yml
bors-ng now consider skipped job as fail.
https://github.com/bors-ng/bors-ng/issues/1115
=> ci: remove ci-failure

crossbeam-channel/tests/golang.rs
Rust port [chan1.go](https://github.com/golang/go/blob/master/test/ken/chan1.go)
Based on an ask in #201
=> Port Golang chan1.go Test

crossbeam-channel/tests/ready.rs, crossbeam-channel/tests/select.rs, crossbeam-skiplist/benches/btree.rs, crossbeam-skiplist/benches/hash.rs, crossbeam-skiplist/benches/skiplist.rs, crossbeam-skiplist/benches/skipmap.rs, crossbeam-skiplist/examples/simple.rs, crossbeam-utils/src/thread.rs, crossbeam-utils/tests/sharded_lock.rs
- Replace `while !false` with `loop`
- Remove needless cfg
- Remove needless cast
- Replace `assert!(false)` with `panic!`
=> Minor cleanup

.github/bors.toml
https://bors.tech/documentation
> If set to true, and if the PR branch is on the same repository that bors-ng itself is on, the branch will be deleted.
=> bors: set delete_merged_branches = true

crossbeam-epoch/src/atomic.rs, crossbeam-epoch/src/epoch.rs, crossbeam-epoch/src/lib.rs, crossbeam-epoch/src/sync/list.rs, crossbeam-epoch/src/sync/queue.rs, crossbeam-epoch/tests/loom.rs, crossbeam-skiplist/src/base.rs, crossbeam-utils/src/atomic/atomic_cell.rs
Instead of changing the argument of `Atomic::compare_and_set(_weak)`, add new methods `Atomic::compare_exchange(_weak)` that always use two orderings.
This PR adds:
- `Atomic::compare_exchange`
Unlike `compare_and_set`, this always receive two orderings.
- `Atomic::compare_exchange_weak`
Unlike `compare_and_set_weak`, this always receive two orderings.
- `CompareExchangeError` (error returned by `Atomic::compare_exchange(_weak)`)
The definition is the same as `CompareAndSetError`, just renamed `CompareExchangeError`.
This PR deprecates:
- [`Atomic::compare_and_set`](https://docs.rs/crossbeam-epoch/0.9/crossbeam_epoch/struct.Atomic.html#method.compare_and_set)
- [`Atomic::compare_and_set_weak`](https://docs.rs/crossbeam-epoch/0.9/crossbeam_epoch/struct.Atomic.html#method.compare_and_set_wea …
=> Add Atomic::compare_exchange(_weak) and deprecate Atomic::compare_and_set(_weak)

crossbeam-utils/src/cache_padded.rs
This updates alignment of `CachePadded` on the following architectures based on golang's [`CacheLinePadSize`](https://github.com/golang/go/blob/3510a1e32cbc86b73db143aefcc00aadc44c27bd/src/internal/cpu/cpu.go#L20).
- On [powerpc64](https://github.com/golang/go/blob/3dd58676054223962cd915bb0934d1f9f489d4d2/src/internal/cpu/cpu_ppc64x.go#L9), use 128-byte alignment.
- On [arm](https://github.com/golang/go/blob/3dd58676054223962cd915bb0934d1f9f489d4d2/src/internal/cpu/cpu_arm.go#L7), [mips](https://github.com/golang/go/blob/3dd58676054223962cd915bb0934d1f9f489d4d2/src/internal/cpu/cpu_mips.go#L7), [mips64](https://github.com/golang/go/blob/3dd58676054223962cd915bb0934d1f9f489d4d2/src/internal/cpu/cpu_mips64x.go#L9), and [riscv64](https://github.com/golang/go/blob/3dd58676054223962cd915bb0934d …
=> CachePadded: update alignment based on golang's CacheLinePadSize

crossbeam-channel/src/channel.rs, crossbeam-channel/src/counter.rs, crossbeam-channel/src/flavors/array.rs, crossbeam-channel/src/flavors/at.rs, crossbeam-channel/src/flavors/list.rs, crossbeam-channel/src/flavors/mod.rs, crossbeam-channel/src/flavors/never.rs, crossbeam-channel/src/flavors/tick.rs, crossbeam-channel/src/flavors/zero.rs, crossbeam-channel/src/lib.rs, crossbeam-channel/src/select.rs, crossbeam-channel/src/utils.rs, crossbeam-channel/src/waker.rs, crossbeam-deque/src/lib.rs, crossbeam-epoch/src/deferred.rs, crossbeam-epoch/src/epoch.rs, crossbeam-epoch/src/internal.rs, crossbeam-epoch/src/lib.rs, crossbeam-epoch/src/sync/list.rs, crossbeam-epoch/src/sync/mod.rs, crossbeam-epoch/src/sync/queue.rs, crossbeam-queue/src/lib.rs, crossbeam-skiplist/src/lib.rs, crossbeam-utils/src/atomic/seq_lock.rs, crossbeam-utils/src/atomic/seq_lock_wide.rs, crossbeam-utils/src/lib.rs, crossbeam-utils/src/sync/parker.rs, src/lib.rs
`unreachable_pub` lint warns items that are marked as `pub` but are not actually included in the public API, and suggests using `pub(crate)` instead.
`pub(crate)` is a bit more verbose than `pub`, but this should make it easier to review changes that make it difficult to tell if it will break API or not just by looking at the diff like https://github.com/crossbeam-rs/crossbeam/pull/617#discussion_r548370194. Especially, there are many such codes in crossbeam-channel and crossbeam-epoch. (Hopefully, after this patch, we can basically consider all items marked `pub` are public APIs, except for items that have been explicitly hidden from the public API by `#[doc(hidden)]`.)
This lint is known to have some false positives, but the crossbeam doesn't seem to be affected.
=> Apply unreachable_pub lint

crossbeam-utils/src/atomic/mod.rs, src/lib.rs
Both [`sync`](https://docs.rs/crossbeam/0.8.0/crossbeam/sync/index.html) and [`queue`](https://docs.rs/crossbeam/0.8.0/crossbeam/queue/index.html) modules have similar docs.
=> Add list of main items to docs of utils and atomic modules

crossbeam-utils/tests/cache_padded.rs
This test fails on architectures that use 32-byte alignment as assuming the alignment of `CachePadded` is 64+.
https://github.com/crossbeam-rs/crossbeam/blob/a66fe72b224e0864f66360778d611a06c7234771/crossbeam-utils/tests/cache_padded.rs#L25-L31
=> Fix CachePadded test

crossbeam-utils/src/backoff.rs, crossbeam-utils/src/lib.rs
`spin_loop_hint` is deprecated in 1.51. (rust-lang/rust#80966)
However, the alternative (`hint::spin_loop`) requires Rust 1.49+, so ignore deprecated warnings for now.
=> Ignore deprecated warnings on spin_loop_hint

crossbeam-skiplist/src/base.rs, crossbeam-skiplist/src/lib.rs, crossbeam-skiplist/src/map.rs
As per https://github.com/crossbeam-rs/crossbeam/issues/503#issuecomment-631679442, I'm writing the docs for `crossbeam-skiplist`. 
Checklist:
I also have some thoughts about the API:
* `Entry`'s name is misleading; it's not the same as the standard library's map entry API. A name like `Ref` might be more suitable, to align with `RefCell`. 
* `set::Entry` could implement `Deref<Target=T>` for convenience. 
* I see the base `SkipList` struct is exposed, though I'm not sure if it belongs in the public API.
=> Add initial docs to crossbeam-skiplist

Cargo.toml, crossbeam-channel/Cargo.toml, crossbeam-deque/Cargo.toml, crossbeam-epoch/Cargo.toml, crossbeam-queue/Cargo.toml, crossbeam-skiplist/Cargo.toml, crossbeam-utils/Cargo.toml
Since 1.46 (rust-lang/cargo#8277), cargo can automatically detect the value of the readme field.
=> Remove readme field from Cargo.toml

.github/bors.toml
This reverts commit c9f244573c4d3ab8ba76367156aec1d446c835d8.
If GitHub's "Automatically delete head branches" setting is enabled,
"delete_merged_branches = true" setting is actually not needed.
=> Revert "bors: set delete_merged_branches = true"

crossbeam-skiplist/src/set.rs, crossbeam-skiplist/tests/set.rs
*This originally suggested by @caelunshun in https://github.com/crossbeam-rs/crossbeam/pull/535#issue-440783380.*
cc #635
=> impl Deref for set::Entry

ci/crossbeam-epoch-loom.sh, crossbeam-epoch/Cargo.toml, crossbeam-epoch/src/atomic.rs, crossbeam-epoch/src/collector.rs, crossbeam-epoch/src/default.rs, crossbeam-epoch/src/deferred.rs, crossbeam-epoch/src/internal.rs, crossbeam-epoch/src/lib.rs, crossbeam-epoch/src/sync/list.rs, crossbeam-epoch/src/sync/queue.rs, crossbeam-epoch/tests/loom.rs, crossbeam-utils/Cargo.toml, crossbeam-utils/src/atomic/atomic_cell.rs, crossbeam-utils/src/atomic/consume.rs, crossbeam-utils/src/atomic/mod.rs, crossbeam-utils/src/lib.rs, crossbeam-utils/src/sync/mod.rs, src/lib.rs
It matches with the convention that *will* be documented in `loom`. See https://github.com/crossbeam-rs/crossbeam/pull/487#issuecomment-753800120 for more.
r? @jeehoonkang @jonhoo
=> Rename cfg(loom_crossbeam) to cfg(crossbeam_loom)

crossbeam-skiplist/src/base.rs, crossbeam-skiplist/src/lib.rs, crossbeam-skiplist/src/map.rs, crossbeam-skiplist/src/set.rs
This is the main blocker for the crossbeam-skiplist 0.1 release.
cc #635
=> Add docs for SkipSet and SkipList

.github/workflows/ci.yml, ci/san.sh, ci/test.sh, ci/tsan, crossbeam-channel/tests/tick.rs, crossbeam-epoch/src/collector.rs, crossbeam-epoch/src/internal.rs
This adds AddressSanitizer/MemorySanitizer/ThreadSanitizer tests to CI.
See #589 (tsan: data race in deque), #644 (tsan: data race in atomic), and #614 (asan: memory leak in skiplist) for issues reported by sanitizers.
Closes #154
Closes #589
Closes #644 
Refs: 
- https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/sanitizer.html
- https://github.com/google/sanitizers/wiki
=> Run sanitizers on CI

ci/crossbeam-epoch-loom.sh, crossbeam-epoch/Cargo.toml, crossbeam-epoch/src/lib.rs, crossbeam-epoch/tests/loom.rs, crossbeam-utils/Cargo.toml
The loom dependency will never compile unless users enable cfg, but the way cargo and crates.io handle cfg-ed dependencies is not very good and confuses users.
This issue seems to work around by the way proposed by @matklad in https://github.com/crossbeam-rs/crossbeam/pull/487#issuecomment-783385606.
So this PR uses that workaround.
Closes #665
r? @jeehoonkang @jonhoo
=> Make loom dependency optional

crossbeam-skiplist/src/base.rs
Closes #671. Closes #672.
The first one is like https://github.com/crossbeam-rs/crossbeam/commit/a6de0ca23b5364d2acc876f6e3d74cb8ab4d7b4a, but the previous commit missed fixing `RefRange`.
The second problem is that `remove` increases the ref count but not returning the entry when the tower is not marked by the current thread. So the leak should be fixed if we always return the entry once the ref count is increased.
=> Fix two memory leaks in crossbeam-skiplist

ci/san.sh, crossbeam-skiplist/tests/map.rs, crossbeam-skiplist/tests/set.rs
asan leak check is currently disabled for all crates, but only skiplist actually has memory leaks.
This PR minimizes the scope that asan leak check is disabled and enables asan leak check for most crates and test.
This PR also adds tests for memory leaks recently fixed.
=> Adjust scope of asan leak check

crossbeam-channel/src/channel.rs, crossbeam-channel/src/flavors/list.rs
If all receivers are dropped, the memory hold by channel will only be
dropped when all senders are also dropped. If there are too many
channels the memory leak can be significant.
=> channel: discard messages eagerly

README.md, crossbeam-channel/README.md, crossbeam-deque/README.md, crossbeam-epoch/README.md, crossbeam-queue/README.md, crossbeam-skiplist/README.md, crossbeam-utils/README.md
Fixes #681 
The correct link is https://discord.com/invite/JXYwgWZ.
=> Fix discord invite link

ci/check-features.sh
I'm planning to increase the Rust version required for the installation of cargo-hack from 1.36 to 1.40. (cargo-hack is usually runnable with Cargo versions older than the Rust version required for installation. Rust 1.36 will continue to be supported after the increase the Rust version required for the installation of cargo-hack has been increased.)
=> Use stable compiler to installing cargo-hack

crossbeam-epoch/src/atomic.rs
=> epoch: Correct handling of null ptr returned from alloc::alloc

crossbeam-epoch/src/lib.rs
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
--> crossbeam-epoch/src/atomic.rs:313:6
|
313 | impl<T: ?Sized + Pointable> Atomic<T> {
|      ^
|
= note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information
= help: add `#![feature(const_fn_trait_bound)]` to the crate attributes to enable
=> Use feature(const_fn_trait_bound) instead of feature(const_fn)

crossbeam-channel/examples/fibonacci.rs, crossbeam-channel/examples/stopwatch.rs, crossbeam-channel/tests/golang.rs, crossbeam-deque/tests/fifo.rs, crossbeam-deque/tests/injector.rs, crossbeam-deque/tests/lifo.rs, crossbeam-epoch/src/atomic.rs, crossbeam-skiplist/tests/base.rs, crossbeam-utils/tests/cache_padded.rs, crossbeam-utils/tests/sharded_lock.rs
I feel that some lints are too strict for test code, so this will only fix some warnings which I think are reasonable.
=> Fix some clippy warnings in tests and examples

crossbeam-channel/benchmarks/go.go
Per the [crossbeam benchmark configuration](https://github.com/crossbeam-rs/crossbeam/blob/master/crossbeam-channel/benchmarks/README.md) the `select_both` function is defined as: 
> select_both: T threads send N / T messages each by selecting over T channels. T other threads receive N / T messages each by selecting over the T channels.
Previously, the `select_both` function in [go.go](https://github.com/crossbeam-rs/crossbeam/blob/3e83987f258ab85a6573704ba538f2efdfe587c1/crossbeam-channel/benchmarks/go.go#L128) did not utilize the `select` statement while sending messages. Added the use of the select statement.
=> fixed go.go to properly select over channels during the put operation in select_both

crossbeam-epoch/src/atomic.rs
=> epoch: Fix UB in Pointable impl of [MaybeUninit<T>]

.github/workflows/ci.yml
This reverts commit 806ac6b62bdd5a5cebedd6fb41a7d7800c1d19ec (#700).
That PR did not fix the problem correctly. https://github.com/crossbeam-rs/crossbeam/runs/2687386418?check_suite_focus=true
=> Revert "Fix windows CI"

crossbeam-utils/src/atomic/atomic_cell.rs
Equivalent of [`std::sync::atomic::AtomicN::fetch_update`](https://doc.rust-lang.org/nightly/core/sync/atomic/struct.AtomicUsize.html#method.fetch_update) that stabilized in Rust 1.45.
=> Add AtomicCell::fetch_update

crossbeam-deque/src/deque.rs
Stealer only has the method `is_empty()` at the moment, but it would also be useful to check the size of the deque to e.g. steal from the longest deque.
Closes #572
=> add len() to Stealer

crossbeam-epoch/src/atomic.rs
Equivalent of [`AtomicN::fetch_update`](https://doc.rust-lang.org/nightly/core/sync/atomic/struct.AtomicUsize.html#method.fetch_update) and [`AtomicCell::fetch_update`](https://github.com/crossbeam-rs/crossbeam/pull/704).
=> Add Atomic::fetch_update

ci/dependencies.sh
dev-dependencies may raise version requirements. Ideally, remove them before run `cargo update -Z mimimal-version`.
See also https://github.com/tokio-rs/tokio/pull/3131#discussion_r521621961.
=> Correct minimal versions check

crossbeam-channel/benchmarks/Cargo.toml
https://github.com/crossbeam-rs/crossbeam/runs/2755265709?check_suite_focus=true
```
error: document output filename collision
The lib `crossbeam-channel` in package `crossbeam-channel v0.5.1 (/home/runner/work/crossbeam/crossbeam/crossbeam-channel)` has the same name as the bin `crossbeam-channel` in package `benchmarks v0.1.0 (/home/runner/work/crossbeam/crossbeam/crossbeam-channel/benchmarks)`.
Only one may be documented at once since they output to the same path.
Consider documenting only one, renaming one, or marking one with `doc = false` in Cargo.toml.
```
=> Fix cargo doc failure

crossbeam-channel/src/context.rs
The newer 'f' only captures a mut reference of the former 'f' to make itself becomes a FnMut.So, the 'move' keyword here seems unnecessary.
=> remove unnecessary 'move' keyword

crossbeam-skiplist/src/base.rs, crossbeam-skiplist/src/map.rs, crossbeam-skiplist/tests/base.rs, crossbeam-skiplist/tests/map.rs
get_or_insert_with function allows lazy creation of default value. Default values may be heavy objects, lazy creation doesn't create un-necessary objects when key is already there in the data structure.
=> added get_or_insert_with function

crossbeam-deque/src/lib.rs
=> v0.7: Fix deque steal race condition

Cargo.toml, crossbeam-channel/Cargo.toml, crossbeam-deque/Cargo.toml, crossbeam-epoch/Cargo.toml, crossbeam-queue/Cargo.toml, crossbeam-skiplist/Cargo.toml, crossbeam-utils/Cargo.toml
https://doc.rust-lang.org/cargo/reference/manifest.html#the-documentation-field
> If no URL is specified in the manifest file, crates.io will
> automatically link your crate to the corresponding docs.rs page.
=> Remove doc URL from Cargo.toml

crossbeam-skiplist/src/base.rs
`SkipList` may leak memory when calling `pop_front` (or `pop_back`) concurrently. This is because we forget to decrement the reference count of `RefEntry` when the deletion of an element fails in the `pop_front`/`pop_back`.
This PR fixes it by calling `release` when the removal fails.
=> Fix memory leaks in pop_front and pop_back

crossbeam-skiplist/src/base.rs, crossbeam-skiplist/src/map.rs, crossbeam-skiplist/tests/map.rs
This PR updates the implementation of `RefIter` so that `head` and `tail` always hold the last value returned from `next` and `next_back` respectively. `None` means there has been no invocation.
This PR also tweaks how we handle reference count in RefIter, and adds `Drop` implementation to `Iter` which is a consumer of `RefIter` to avoid leaking memory.
Closes #737.
=> Keep skiplist iterator ordered

crossbeam-skiplist/src/base.rs, crossbeam-skiplist/src/map.rs, crossbeam-skiplist/tests/map.rs
This PR fixes two issues in skiplist Range API.
1. `next_back` does not work as expected
2. Range can leak memory
We fix the first one by using the correct bound when searching for the upper/lower bound (3406d84) and the second one by the same approach used in #738 (a7caaf1).
=> Fix skiplist Range API

Cargo.toml, crossbeam-channel/Cargo.toml, crossbeam-deque/Cargo.toml, crossbeam-epoch/Cargo.toml, crossbeam-queue/Cargo.toml, crossbeam-skiplist/Cargo.toml, crossbeam-utils/Cargo.toml
This field is soft-deprecated, cargo no longer generates this field by default, and Rust's official services no longer reference this field at all.
See [RFC3052](https://rust-lang.github.io/rfcs/3052-optional-authors-field.html) for more.
=> Remove authors field from Cargo.toml

.github/workflows/ci.yml
This reverts commit bce74ca9a5405c31204894a8c4b8f13d16fa9686.
cargo-hack fixed the problem in [0.5.9](https://github.com/taiki-e/cargo-hack/releases/tag/v0.5.9).
=> Revert "Disable feature check on MSRV"

.github/workflows/ci.yml, ci/check-features.sh, ci/dependencies.sh
Use [taiki-e/install-action](https://github.com/taiki-e/install-action) to install prebuilt binaries. This makes the installation faster and may avoid the impact of [problems caused by upstream changes](https://github.com/tokio-rs/bytes/issues/506).
=> Make installation of cargo-hack faster and robust

crossbeam-channel/src/flavors/array.rs, crossbeam-queue/src/array_queue.rs
This fixes the following stacked borrows violation.
```sh
MIRIFLAGS="-Zmiri-tag-raw-pointers" cargo miri test -p crossbeam-queue
```
```text
error: Undefined Behavior: trying to reborrow for Unique at alloc67500, but parent tag <180167> does not have an appropriate item in the borrow stack
--> /Users/taiki/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/raw.rs:130:14
|
130 |     unsafe { &mut *ptr::slice_from_raw_parts_mut(data, len) }
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ trying to reborrow for Unique at alloc67500, but parent tag <180167> does not have an appropriate item in the borrow stack
|
= help: this indicates a potential bug in the program: it performed an invalid operation, but the rules it violated are still …
```
=> Use Box::into_raw instead of mem::forget-in-disguise

ci/miri.sh, crossbeam-channel/src/context.rs, crossbeam-channel/src/flavors/zero.rs, crossbeam-channel/src/select.rs, crossbeam-channel/src/waker.rs
This fixes #762 and another stacked borrows violation that seems to have been made detectable by the fix of #762.
=> channel: Remove ptr-to-int casts

crossbeam-utils/src/atomic/atomic_cell.rs
They are covered by branches of AtomicU32/AtomicU64.
=> Remove unneeded branch from atomic! and atomic_is_lock_free

crossbeam-utils/src/atomic/atomic_cell.rs
This adds `AtomicCell<{i,u}64>::{fetch_add,fetch_sub,fetch_and,fetch_or,fetch_xor}` on targets that do not support `Atomic{I,U}64`.
This also adds `AtomicCell<{i,u}128>::{fetch_add,fetch_sub,fetch_and,fetch_or,fetch_xor}`.
These were provided in older versions of crossbeam-utils, but were unintentionally removed in 0.8.0 (https://github.com/crossbeam-rs/crossbeam/commit/11fbf05968ba702b61b6c61e32fdd4250b2c0aba).
=> Support AtomicCell<*64> arithmetics on targets that do not support Atomic*64

crossbeam-channel/src/flavors/array.rs, crossbeam-channel/tests/array.rs, crossbeam-queue/src/array_queue.rs
Before #458, since destructors could be called on elements, the correct way was to convert the Vec to a pointer, save it, and then [deallocate it as a Vec with zero length](https://github.com/crossbeam-rs/crossbeam/blob/28ad2b7e015832b47db7e389dd9ebce3e94b3adb/crossbeam-channel/src/flavors/array.rs#L549-L552). However, after #458, destructors of the elements wrapped by MaybeUninit are not called, so there is no need to save the Vec/boxed slice as a pointer. This removes the unsafe code that has caused several (potential) unsoundnesses in the past (#500, #533, #763).
=> Reduce unsafe code in array queue/bounded channel

.github/workflows/ci.yml, ci/test.sh, crossbeam-utils/tests/atomic_cell.rs
Test 32-bit target that does not have AtomicU64/AtomicI64.
This also adds a test for the regression that #767 caught.
=> Add mips-unknown-linux-gnu to CI

crossbeam-epoch/src/deferred.rs
This situation can be observed by running `MIRIFLAGS="-Zmiri-check-number-validity" cargo miri test` in `crossbeam/crossbeam-deque`:
```
test is_empty ... error: Undefined Behavior: type validation failed at .value[0]: encountered uninitialized bytes
--> /home/ben/crossbeam/crossbeam-epoch/src/deferred.rs:49:27a
|
49 |                     data: data.assume_init(),
|                           ^^^^^^^^^^^^^^^^^^ type validation failed at .value[0]: encountered uninitialized bytes
|
```
In the crossbeam-deque test suite, a `Deferred` was created from a `FnOnce` which is smaller than the `Data`. This makes the call to `MaybeUninit::assume_init()` immediate UB (the reference to it created upon call is probably UB too). [The docs for `MaybeUninit::assume_init()`](https://doc.rust-lang.org/stable …
=> Don't call assume_init on Deferred's Data

crossbeam-utils/src/atomic/atomic_cell.rs
The alignment of u64/i64 on a 32-bit target can be smaller than AtomicU64/AtomicI64.
32-bit targets without Atomic*64 (https://github.com/crossbeam-rs/crossbeam/pull/767) and 64-bit targets are not affected by this issue.
=> Fix unsoundness of AtomicCell<*64> arithmetics on 32-bit targets that support Atomic*64

crossbeam-channel/src/err.rs, crossbeam-channel/src/flavors/array.rs, crossbeam-channel/src/flavors/at.rs, crossbeam-channel/src/flavors/never.rs, crossbeam-channel/src/flavors/tick.rs, crossbeam-channel/src/flavors/zero.rs, crossbeam-epoch/src/atomic.rs, crossbeam-epoch/src/deferred.rs, crossbeam-utils/src/atomic/atomic_cell.rs
Most of these lints have been downgraded to be allowed by default.
=> Remove unnecessarily allowed lints

crossbeam-epoch/src/lib.rs, crossbeam-utils/src/atomic/atomic_cell.rs, crossbeam-utils/src/atomic/mod.rs
We cannot provide AtomicCell under `cfg(crossbeam_loom)` because loom's atomic types have a different in-memory representation than the underlying type. (https://github.com/tokio-rs/loom/pull/253)
https://github.com/crossbeam-rs/crossbeam/blob/bd83e1f2328e90298fc8a2f535a25d94ece09152/crossbeam-utils/src/atomic/atomic_cell.rs#L35-L42
fyi @jonhoo
=> Do not provide AtomicCell when cfg(crossbeam_loom) is enabled

crossbeam-queue/src/array_queue.rs, crossbeam-queue/tests/array_queue.rs
This is an attempt to implement a straightforward MPMC ring-buffer and close #680.
This proposal adds a new method `push_or_swap` to `ArrayQueue`, that atomically swaps the oldest element when the queue is full, instead of returning `Err` back to the caller like `push` does. As such, `push_or_swap` never fails to insert the element into the queue.
I couldn't find any benchmarks I could run, (am I missing anything obvious?), however I did run benchmarks from [ring-channel](https://github.com/brunocodutra/ring-channel) where I compared this implementation against an emulation of a ring-buffer, that keeps popping elements until pushing succeeds, i.e. something like the following:
```
while let Err(v) = q.push(value) {
q.pop();
value = v;
}
```
I got the results below on my machine, which …
=> Add fn force_push to ArrayQueue 

crossbeam-epoch/Cargo.toml, crossbeam-epoch/build.rs, crossbeam-epoch/src/atomic.rs, crossbeam-epoch/src/lib.rs
const_fn_trait_bound has been stabilized on Rust 1.61.
=> Update to stabilized const_fn_trait_bound

crossbeam-channel/src/waker.rs
This should result in the same behavior as before 10009bd.
This works around an upstream bug related to TLS access on aarch64 linux, which was [reported in firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1757571).
=> channel: Do not call current_thread_id inside iteration

crossbeam-utils/src/thread.rs
This PR is related to issue #792. Sorry for the delay!
I also want to double check that this is expected behaviour. I quickly made a
test crate:
`main.rs`:
```rust
use crossbeam_utils::thread;
fn main() {
let scoped_threads_result = thread::scope(|scope| {
scope.spawn(move |_| {
panic!("oh no!");
});
});
dbg!(scoped_threads_result.unwrap());
}
```
`Cargo.toml`:
```toml
[package]
name = "crossbeam-test"
version = "0.1.0"
edition = "2021"
[dependencies]
crossbeam-utils = "0.8.8"
[profile.release]
panic = "abort"
```
This gives:
```
cargo run --release
Finished release [optimized] target(s) in 0.00s
Running `target/release/crossbeam-test`
thread '<unnamed>' panicked at 'oh no!', src/main.rs:6:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
whereas without …
=> Add caveat documentation on panicking.

crossbeam-channel/src/flavors/array.rs, crossbeam-channel/src/flavors/list.rs
As access to `&mut self` in `Drop` impls gives exclusive access, it's
unnecessary to atomically load `self.head` and `self.tail` there.
=> channel: use `AtomicUsize::get_mut` in `flavors::{array,list}::Channel::drop`

crossbeam-epoch/Cargo.toml, crossbeam-epoch/src/default.rs, crossbeam-epoch/src/lib.rs, crossbeam-utils/Cargo.toml, crossbeam-utils/src/sync/sharded_lock.rs
=> Replace lazy_static with once_cell

crossbeam-channel/src/channel.rs
Increase time margin for checking event times to make the doc test more reliable
ref #825
=> Make doc test for tick channel more reliable

crossbeam-deque/tests/injector.rs, crossbeam-deque/tests/lifo.rs
This is a better way to do #829 
Miri does not have a pre-emptive scheduler, so once the execution falls into a spin loop it'll hang forever: https://github.com/rust-lang/miri/issues/1388
Similar measures (`yield_now()`) are already present in [some other tests](https://github.com/crossbeam-rs/crossbeam/blob/master/crossbeam-queue/tests/array_queue.rs), but it's missing here
=> Add spin loop hints in tests for Miri

crossbeam-channel/src/channel.rs, crossbeam-channel/src/select.rs, crossbeam-channel/src/select_macro.rs
The fix provides explicit links to macro rules in docs because they [are not resolved globally anymore](https://github.com/rust-lang/rust/pull/96676).
=> Fix links to macro rules in docs

crossbeam-channel/src/flavors/zero.rs, crossbeam-channel/src/utils.rs, crossbeam-channel/src/waker.rs
Addresses one of @thomcc's reviews in https://github.com/rust-lang/rust/pull/93563#discussion_r799137958 (sorry for the late response!)
Historically, the use of spinlock was introduced when the dependency on parking_lot was removed (https://github.com/crossbeam-rs/crossbeam/commit/5208895dbcf568fc92e70b1644217dfe1b634e51).
However, given that it is used in Waker, which includes vectors that may be reallocated, using mutex seems to be the right choice here.
r? @ibraheemdev
bors d=ibraheemdev
=> channel: Replace Spinlock with Mutex

README.md
This is _extremely_ minor, but I was clicking through the links in the README and noticed that the link to the CoC is out of date (it was moved to the website, and the GitHub document points to the website). Figured I'd remove that one step of indirection ✌️
=> readme: fix Code of Conduct link

crossbeam-utils/src/atomic/atomic_cell.rs, crossbeam-utils/tests/atomic_cell.rs
Fixes #833
Note: This contains two breaking changes:
- Unsized values are no longer allowed.
This is because `MaybeUninit` doesn't allow it.
- `AtomicCell` now implements `Drop`.
This is because `MaybeUninit` prevents `T` from being dropped, so we need to implement `Drop` for `AtomicCell` to avoid leaks of non-`Copy` types.
Breakages are allowed because this is a soundness bug fix. However, given the amount of breakage, we would not be able to yank the affected releases and would only create an advisory.
=> Use `UnsafeCell<MaybeUninit<T>>` in AtomicCell

ci/miri.sh, crossbeam-channel/tests/array.rs, crossbeam-channel/tests/golang.rs, crossbeam-channel/tests/list.rs, crossbeam-channel/tests/mpsc.rs, crossbeam-channel/tests/thread_locals.rs, crossbeam-channel/tests/zero.rs, crossbeam-deque/src/deque.rs, crossbeam-queue/tests/array_queue.rs, crossbeam-queue/tests/seg_queue.rs, crossbeam-utils/tests/wait_group.rs
Miri has a [work-around](https://github.com/rust-lang/miri/pull/2248) for https://github.com/rust-lang/rust/issues/55005 now.
Also, "check-number-validity" is on by default these days.  And I am not sure why "compare-exchange-weak-failure-rate=0.0" was set so let's see what happens when we remove it. :)
=> Miri: enable preemption again

crossbeam-epoch/src/atomic.rs
Sometimes, I have run into times when I have had an `Atomic` which I know to be either null or valid, and I want to convert it into an `Owned`. As far as I can tell, there is no way to do this without converting through a `Shared`, which comes at the const of an additional atomic load. This pull request also adds the same method to `Shared` for symmetry.
This pull request adds the following methods:
```rust
impl<T: ?Sized + Pointable> Owned<T> {
pub unsafe fn try_into_owned(self) -> Option<Owned<T>>;
}
impl<T: ?Sized + Pointable> Shared<'_, T> {
pub unsafe fn try_into_owned(self) -> Option<Owned<T>>;
}
```
=> Add {Atomic, Shared}::try_into_owned

crossbeam-deque/src/deque.rs, crossbeam-queue/src/array_queue.rs, crossbeam-queue/src/seg_queue.rs
Similar to #811, but for deque and queue.
=> Use get_mut instead of atomic load in Drop impls

crossbeam-epoch/src/atomic.rs, crossbeam-skiplist/src/base.rs
```
warning: deref which would be done by auto-deref
--> crossbeam-epoch/src/atomic.rs:1715:43
|
1715 |         let arr: &[MaybeUninit<usize>] = &*owned;
|                                           ^^^^^^ help: try this: `owned`
|
= note: `#[warn(clippy::explicit_auto_deref)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#explicit_auto_deref
warning: deref which would be done by auto-deref
--> crossbeam-skiplist/src/base.rs:1045:21
|
1045 |                     (*n).refs_and_height
|                     ^^^^ help: try this: `n`
|
= note: `#[warn(clippy::explicit_auto_deref)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#explicit_auto_deref
```
=> Fix clippy::explicit_auto_deref warning

crossbeam-epoch/src/internal.rs
- Revert #552 to mitigate the risk of segmentation faults in buggy downstream implementations (see #869)
- Reduce MAX_OBJECTS on cfg(miri)
=> epoch: Adjust MAX_OBJECTS

Cargo.toml, ci/miri.sh, crossbeam-epoch/src/atomic.rs, crossbeam-epoch/src/collector.rs, crossbeam-epoch/src/internal.rs, crossbeam-epoch/src/lib.rs, tests/subcrates.rs
Use [this hack](https://github.com/rust-lang/miri/issues/1866#issuecomment-985802751) to fix compatibility issues with Miri (see https://github.com/crossbeam-rs/crossbeam/pull/490#issuecomment-755435349 for details). 
Due to the https://github.com/crossbeam-rs/crossbeam/issues/545, still not compatible with stacked borrows. This will be fixed by the subsequent PR (#871).
Note: this is a breaking change because changes API of Pointable and Pointer traits
Fixes #579
=> epoch: Remove ptr-to-int casts

crossbeam-epoch/src/atomic.rs, crossbeam-epoch/src/lib.rs
=> epoch: Seal Pointer trait

crossbeam-channel/tests/golang.rs, crossbeam-deque/src/lib.rs, crossbeam-skiplist/tests/base.rs, crossbeam-skiplist/tests/map.rs, crossbeam-utils/src/sync/wait_group.rs
clippy::mutex_atomic has been moved to the allowed by default group in Rust 1.60 (https://github.com/rust-lang/rust-clippy/pull/8260).
clippy::question_mark bug has been fixed in Rust 1.59 (https://github.com/rust-lang/rust-clippy/pull/8080).
=> Remove unnecessary allowed lints

crossbeam-channel/src/channel.rs
Add note that the channel is multi-producer multi-consumer to the functions' docs. Also point to the parent module docs since they contain a lot of info on how to use the channel. These changes make functions' docs more self-contained (previously one needed to know to look at the module docs to discover this info).
=> Improve docs of channel creation functions

.github/workflows/ci.yml, crossbeam-epoch/Cargo.toml, crossbeam-epoch/src/default.rs, crossbeam-epoch/src/lib.rs, crossbeam-epoch/src/sync/mod.rs, crossbeam-epoch/src/sync/once_lock.rs, crossbeam-utils/Cargo.toml, crossbeam-utils/src/sync/mod.rs, crossbeam-utils/src/sync/once_lock.rs, crossbeam-utils/src/sync/sharded_lock.rs
Replace `once_cell` with our own `OnceLock` that based on unstable `std::sync::OnceLock` due to MSRV issue[^1].
This also fixes #856 due to windows-gnu LTO issue.
[^1]: [The current readme says crossbeam support at least 6 months old compilers](https://github.com/crossbeam-rs/crossbeam/blob/e54f01e7a7e3913407e817ce3e578a76b6392ef1/README.md#compatibility), but that is a minimum guarantee and is [actually more conservative](https://github.com/crossbeam-rs/crossbeam/pull/877#issuecomment-1192585582).
=> Remove dependency on once_cell and work around windows-gnu LTO issue

crossbeam-channel/tests/golang.rs, crossbeam-epoch/src/internal.rs, crossbeam-skiplist/benches/skiplist.rs, crossbeam-utils/src/sync/wait_group.rs
```
error: deref which would be done by auto-deref
--> crossbeam-utils/src/sync/wait_group.rs:142:29
|
142 |         let count: &usize = &*self.inner.count.lock().unwrap();
|                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `&self.inner.count.lock().unwrap()`
|
= note: `-D clippy::explicit-auto-deref` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#explicit_auto_deref
```
=> Fix newly added clippy warnings

build-common.rs, crossbeam-epoch/build-common.rs, crossbeam-epoch/build.rs, crossbeam-queue/build-common.rs, crossbeam-queue/build.rs, crossbeam-skiplist/build-common.rs, crossbeam-skiplist/build.rs, crossbeam-utils/build-common.rs, crossbeam-utils/build.rs
Some build systems such as the Yocto project define custom rust targets, of the form 'arch-somevendor-linux-{gnu|musl}' (only the 'somevendor' part is custom, the rest matches rust's definitions).
This causes mismatches with crossbeam's lists of targets which are built from the standard rust target list, and always have 'unknown' as the vendor.
This change simply replaces such custom vendors with 'unknown' when the third component of the target is 'linux'.
---
Note from Alex: this is a reworked and hopefully better/more precise/acceptable version of https://github.com/crossbeam-rs/crossbeam/pull/751
=> When building for linux, replace all vendors with 'unknown'

crossbeam-epoch/Cargo.toml
mostly to keep the number of dupes of crates in my dependency graph down
=> crossbeam-epoch: Bump memoffset to 0.7

build-common.rs, crossbeam-epoch/CHANGELOG.md, crossbeam-epoch/Cargo.toml, crossbeam-epoch/build-common.rs, crossbeam-epoch/build.rs, crossbeam-queue/CHANGELOG.md, crossbeam-queue/Cargo.toml, crossbeam-queue/build-common.rs, crossbeam-queue/build.rs, crossbeam-skiplist/build-common.rs, crossbeam-skiplist/build.rs, crossbeam-utils/CHANGELOG.md, crossbeam-utils/Cargo.toml, crossbeam-utils/build-common.rs, crossbeam-utils/build.rs, no_atomic.rs
Backports #922 and #926.
Changes:
- crossbeam-utils 0.8.12 -> 0.8.13
- Update `memoffset` to 0.7. (#926)
- Improve support for custom targets. (#922)
- crossbeam-queue 0.3.6 -> 0.3.7
- Improve support for custom targets. (#922)
- crossbeam-epoch 0.9.11 -> 0.9.12
- Improve support for custom targets. (#922)
Closes #928
=> v0.8: Prepare for the next release

build-common.rs
Currently the build script panic when the target triplets have less than three elements, for example `wasm32-wasi`, this PR fixes that issue.
Fixes #931
=> Fix panicking when target triplets has less than three elements

crossbeam-skiplist/CHANGELOG.md, crossbeam-skiplist/Cargo.toml
Now that all the TODOs in #635 have been resolved, I think we can release the initial version.
There are still some open issues in #635, but I don't think they are blockers of the 0.1 release.
(There are some breaking changes in the master branch, but skiplist is not affected.)
Closes #635
=> Initial release of crossbeam-skiplist

crossbeam-skiplist/src/base.rs
It is related to #878 but doesn't fix it. Miri still complains with this PR.
It fixes the panic on recent toolchains (after https://github.com/rust-lang/rust/pull/92686) when using `-Zbuild-std`.
```
$ RUST_BACKTRACE=1 cargo test -p crossbeam-skiplist -Zbuild-std --target x86_64-unknown-linux-gnu --test map -- smoke
Finished test [unoptimized + debuginfo] target(s) in 0.03s
Running tests/map.rs (target/x86_64-unknown-linux-gnu/debug/deps/map-509dc855f6125f07)
running 1 test
thread 'smoke' panicked at 'unsafe precondition(s) violated: slice::get_unchecked requires that the index is within the slice', /home/yilin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:87:58
stack backtrace:
0: rust_begin_unwind
at …
```
=> Fix get_unchecked panic by raw pointer calculation

.github/bors.toml, .github/workflows/ci.yml, ci/careful.sh
https://github.com/RalfJung/cargo-careful
This allows to catch UB like https://github.com/crossbeam-rs/crossbeam/pull/940.
=> Run cargo-careful in CI

crossbeam-utils/src/thread.rs
Make crossbeam's `scope()` function soft-deprecated in favor of the more efficient `std::thread::scope` that stabilized on Rust 1.63.
Closes #816
Closes #844
=> Make `scope()` function soft-deprecated

crossbeam-channel/src/channel.rs, crossbeam-channel/src/flavors/at.rs, crossbeam-channel/src/flavors/tick.rs, crossbeam-channel/src/select.rs, crossbeam-channel/src/utils.rs, crossbeam-utils/src/sync/parker.rs
Adopts the same approach as the standard library: https://github.com/crossbeam-rs/crossbeam/issues/795#issuecomment-1069514998
r? @ibraheemdev
bors d=ibraheemdev
=> Wait forever on very large timeout

crossbeam-utils/src/sync/sharded_lock.rs
`#[clippy::has_significant_drop]` tells that a structure should be considered when evaluating some lints. Examples of such behavior are the existent `clippy::significant_drop_in_scrutinee` and the soon-to-be-finished https://github.com/rust-lang/rust-clippy/issues/9399.
=> Mark some structures with `#[clippy::has_significant_drop]`

crossbeam-utils/src/cache_padded.rs
- riscv32 is assumed not to exceed the cache line size of riscv64.
- sparc, hexagon, and m68k's cache line sizes are from Linux kernel's __cacheline_aligned ([SMP_CACHE_BYTES, or L1_CACHE_BYTES if SMP_CACHE_BYTES is not set](https://github.com/torvalds/linux/blob/3516bd729358a2a9b090c1905bd2a3fa926e24c6/include/linux/cache.h)).
=> CachePadded: Use 32-byte alignment on riscv32/sparc/hexagon, 16-byte alignment on m68k

.github/workflows/ci.yml, ci/test.sh
[setup-cross-toolchain-action](https://github.com/taiki-e/setup-cross-toolchain-action) is a GitHub Action to set up CI environment for cross-testing, including doctest, without dockers.
This also enables tests for armv7hf on CI.
=> Use setup-cross-toolchain-action instead of cross

.cirrus.yml, .github/workflows/ci.yml
See https://github.com/crossbeam-rs/crossbeam/issues/837 for the motivation.
=> ci: Move armhf test to Cirrus CI

crossbeam-channel/src/flavors/list.rs, crossbeam-channel/tests/list.rs
Receiver disconnection relies on the incorrect assumption that `head.index != tail.index` implies that the channel is initialized (i.e `head.block` and `tail.block` point to allocated blocks). However, it can happen that `head.index != tail.index` and `head.block == null` at the same time which leads to a segfault when a channel is dropped in that state.
This can happen because initialization is performed in two steps. First, the tail block is allocated and the `tail.block` is set. If that is successful `head.block` is set to the same pointer. Importantly, initialization is skipped if `tail.block` is not null.
Therefore we can have the following situation:
1. Thread A starts to send the first value of the channel, observes that `tail.block` is null and begins initialization. It sets …
=> channel: unbounded: synchronize receiver disconnect with initialization 

crossbeam-epoch/Cargo.toml
CC: https://github.com/rust-lang/rust/issues/111839
=> epoch: bump `memoffset` to v0.9

.cirrus.yml, .github/workflows/ci.yml
=> ci: Cirrus CI no longer supports 32-bit mode on ARM Linux runners

ci/miri.sh, crossbeam-epoch/build.rs, crossbeam-queue/build.rs, crossbeam-skiplist/build.rs, crossbeam-utils/build.rs, crossbeam-utils/src/atomic/consume.rs
epoch is not compatible with SB but compatible with TB.
cc https://github.com/crossbeam-rs/crossbeam/pull/871 https://github.com/crossbeam-rs/crossbeam/issues/545 https://github.com/crossbeam-rs/crossbeam/issues/878
=> Miri: Use -Zmiri-tree-borrows instead of -Zmiri-disable-stacked-borrows

crossbeam-utils/tests/wait_group.rs
This test failed in Android's CI system.
=> Remove timing assumptions from `wait_and_drop` test

.github/workflows/ci.yml, crossbeam-channel/tests/golang.rs, crossbeam-epoch/src/atomic.rs, crossbeam-epoch/src/guard.rs, crossbeam-epoch/src/lib.rs
```
error: call to `.clone()` on a reference in this situation does nothing
--> crossbeam-epoch/src/guard.rs:451:38
|
14 |     let dummy = &epoch::unprotected().clone();
|                                      ^^^^^^^^ help: remove this redundant call
|
= note: the type `Guard` does not implement `Clone`, so calling `clone` on `&Guard` copies the reference, which does not do anything and can be removed
note: the lint level is defined here
--> crossbeam-epoch/src/guard.rs:438:9
|
1  | #![deny(warnings, rust_2018_idioms)]
|         ^^^^^^^^
= note: `#[deny(noop_method_call)]` implied by `#[deny(warnings)]`
```
=> Fix noop_method_call warning in doctest

crossbeam-utils/src/cache_padded.rs
As I mentioned in https://github.com/crossbeam-rs/crossbeam/pull/967#issuecomment-1454699153 about the inconsistency here, and [a fix](https://go-review.googlesource.com/c/go/+/526659) was made on the golang side.
> I'm aware of the values defined by the Linux kernel and those defined by us are different for some architectures (e.g., [aarch64](https://github.com/torvalds/linux/blob/0988a0ea791999ebbf95693f2676381825b05033/arch/arm64/include/asm/cache.h#L8), [riscv](https://github.com/torvalds/linux/blob/0988a0ea791999ebbf95693f2676381825b05033/arch/riscv/include/asm/cache.h#L10)), but for now, I have preferred the source we are currently referring to.
=> CachePadded: Use 64-byte alignment on riscv32 and riscv64

crossbeam-epoch/src/internal.rs
The perf c2c data shows lots of cacheline contention were caused by false sharing between epoch and other field in "Local" struct. So use CachePadded class to align it to another cacheline to resolve this issue.
Fixes #1020
=> epoch: Fix false sharing in Local struct

crossbeam-channel/src/flavors/array.rs, crossbeam-channel/src/flavors/list.rs, crossbeam-deque/src/deque.rs, crossbeam-epoch/src/sync/queue.rs, crossbeam-queue/src/array_queue.rs, crossbeam-queue/src/seg_queue.rs, crossbeam-utils/src/sync/once_lock.rs
assume_init_drop requires Rust 1.60, and our MSRV is now 1.61.
=> Use MaybeUninit::assume_init_{drop,read}

crossbeam-utils/src/atomic/atomic_cell.rs
Without it, the actual concurrency level will be small due to false sharing.
(This patch reduces LEN, but the actual concurrency level will be greater.)
=> AtomicCell: Use CachePadded in sharded global locks

.github/workflows/ci.yml, ci/check-features.sh, crossbeam-channel/Cargo.toml, crossbeam-channel/README.md, crossbeam-queue/Cargo.toml, crossbeam-queue/README.md, crossbeam-utils/Cargo.toml, crossbeam-utils/README.md
Only epoch and its dependents require Rust 1.61.
=> Relax MSRV of channel, queue, and utils to 1.60

crossbeam-channel/src/flavors/array.rs, crossbeam-queue/src/array_queue.rs
https://doc.rust-lang.org/std/mem/fn.needs_drop.html
> Note that [drop_in_place](https://doc.rust-lang.org/std/ptr/fn.drop_in_place.html) already performs this check, so if your workload can be reduced to some small number of [drop_in_place](https://doc.rust-lang.org/std/ptr/fn.drop_in_place.html) calls, using this is unnecessary. In particular note that you can [drop_in_place](https://doc.rust-lang.org/std/ptr/fn.drop_in_place.html) a slice, and that will do a single needs_drop check for all the values.
>
> Types like `Vec` therefore just `drop_in_place(&mut self[..])` without using needs_drop explicitly. Types like [HashMap](https://doc.rust-lang.org/std/collections/struct.HashMap.html), on the other hand, have to drop values one at a time and should use this API.
=> Do not iterate elements in bounded queue/channel's destructor when needs_drop returns false

crossbeam-epoch/Cargo.toml, crossbeam-epoch/src/internal.rs
`entry` is the first field of `Local`, so we can remove the needs of `offset_of` by just making `Local` `repr(C)`.
=> epoch: Remove dependency on memoffset

crossbeam-epoch/Cargo.toml
This is unused since https://github.com/crossbeam-rs/crossbeam/pull/1037.
=> epoch: Remove unused autocfg dependency

Cargo.toml, crossbeam-channel/Cargo.toml, crossbeam-channel/src/lib.rs, crossbeam-deque/Cargo.toml, crossbeam-deque/src/deque.rs, crossbeam-deque/src/lib.rs, crossbeam-epoch/Cargo.toml, crossbeam-epoch/src/lib.rs, crossbeam-queue/Cargo.toml, crossbeam-queue/src/lib.rs, crossbeam-skiplist/Cargo.toml, crossbeam-skiplist/src/base.rs, crossbeam-skiplist/src/lib.rs, crossbeam-skiplist/src/map.rs, crossbeam-utils/Cargo.toml, crossbeam-utils/src/atomic/mod.rs, crossbeam-utils/src/lib.rs, src/lib.rs
IMO, while cfg-if is powerful where there are complex mutual exclusion conditions such as "a or b or c or ...", its benefits are not great for simple use cases like ours.
There are also compatibility issues with tools such as rustfmt (and r-a IIRC?), and interoperability with doc_cfg, which is what I plan to use. The rustfmt issue affects not only the code within the macro, but also the module defined within the macro. It is why [tokio's contributing guideline recommends the direct use of rustfmt with git ls-files instead of cargo fmt](https://github.com/tokio-rs/tokio/blob/84c5674c601dfc36ab417ff0ec01763c2dd30a5c/CONTRIBUTING.md#cargo-commands).
=> Remove dependency on cfg-if

crossbeam-channel/benchmarks/lockfree.rs
I am trying to run the lockfree benchmark and plot the results, but the output file has an incorrect name tag.
This causes the lockfree results to disappear. And if both lockfree and crossbeam-channel results coexist, the crossbeam-channel result may be overwritten and corrupted on the benchmark graph.
=> Fix lockfree benchmark output

crossbeam-channel/tests/golang.rs
Ran into this test failure running tests in debug mode on macOS:
```
crossbeam-channel$ cargo test
...
Running tests/golang.rs (/Users/csander/crossbeam/target/debug/deps/golang-5dfea7778bc0a8e8)
running 26 tests
test chan_test::test_chan_send_interface ... ok
test chan_test::test_select_duplicate_channel ... ok
test chan1::main ... ok
test fifo::asynch_fifo ... ok
test fifo::synch_fifo ... ok
test goroutines::main ... ok
test nonblock::main ... ok
test chan_test::test_nonblock_recv_race ... ok
test select4::main ... ok
test select6::main ... ok
test select7::main ... ok
test select::main ... ok
test sieve1::main ... ok
test zerosize::zero_size_array ... ok
test zerosize::zero_size_struct ... ok
test chan_test::test_self_select ... ok
test chan_test::test_nonblock_select_race2 ... ok
test …
```
=> channel tests: don't reset allocated bytes counter

crossbeam-channel/src/flavors/list.rs
Reported in https://github.com/rust-lang/rust/issues/121582. This fixes a race that can occur if a sender installs the first block right after all receivers have disconnected and checked for any existing messages, causing a memory leak.
=> Fix race between block initialization and receiver disconnection

crossbeam-utils/src/cache_padded.rs
Aims to solve #1043.
I have followed the Debug implementation. Some guidance may be required on whether we want to print the inner value or not.
Closes #1043
=> feat: impl Display for CachePadded<T>

crossbeam-skiplist/src/base.rs, crossbeam-skiplist/tests/map.rs, crossbeam-skiplist/tests/set.rs
Fixes https://github.com/crossbeam-rs/crossbeam/issues/1023
After the node on the left has successfully written the new node, then attempt to mark all pointers in the tower
=> skiplist: Fixes #1023

crossbeam-skiplist/tests/map.rs
CI is now taking 3 hours under Miri after https://github.com/crossbeam-rs/crossbeam/pull/1101.
=> Speed Up `concurrent_insert_get_same_key` Under Miri

Cargo.toml, ci/careful.sh
Fix master ci, which is broken due 2 problems:
- the new check-cfg: https://blog.rust-lang.org/2024/05/06/check-cfg.html
- the default linker change: https://blog.rust-lang.org/2024/05/17/enabling-rust-lld-on-linux.html
=> Fix check-cfg-related and rust-lld-related CI failures

crossbeam-channel/src/select.rs, crossbeam-channel/src/select_macro.rs, crossbeam-channel/tests/mpsc.rs, crossbeam-channel/tests/select_macro.rs
~(this is a draft; there's too much of code duplication...)~
much like https://github.com/rust-lang/futures-rs/pull/1976, i want biased select in `crossbeam-channel` as well. :)
=> Add select_biased! macro

Cargo.toml, ci/careful.sh, crossbeam-utils/build.rs
- cargo-careful bug has been fixed in 0.4.2
- move cfgs set by build scripts to cargo:rustc-check-cfg to be able to catch misuse
=> Touch up PR 1110

crossbeam-skiplist/src/base.rs, crossbeam-skiplist/src/map.rs, crossbeam-skiplist/src/set.rs
The `.key()` and `.value()` should return a borrow whose lifetime aligns with the container, instead of the entry itself.
=> Explicitly annotate lifetime of entry methods

crossbeam-channel/src/flavors/list.rs, crossbeam-channel/tests/list.rs
The list channel's `Block::new` was causing a stack overflow because it
held 32 item slots, instantiated on the stack before moving to
`Box::new`. The 32x multiplier made modestly-large item sizes untenable.
That block is now initialized directly on the heap.
References from the `std` channel implementation:
* https://github.com/rust-lang/rust/issues/102246
* https://github.com/rust-lang/rust/pull/132738
=> channel: Create `list::Block` directly on the heap

crossbeam-queue/src/seg_queue.rs
Although a "queue" is typically FIFO, I found it unclear when I first read the doc and I have to read the code to verify it.
=> Clearly document SegQueue is FIFO

crossbeam-channel/src/context.rs
Per https://github.com/crossbeam-rs/crossbeam/pull/1038#issuecomment-2091047279, removes optimistic spinning from Context::wait_until, which is a non-controversial change.
cc @ibraheemdev
=> Remove optimistic spinning from Context::wait_until

.github/workflows/ci.yml, Cargo.toml, ci/miri.sh, ci/san.sh, ci/test.sh, crossbeam-channel/Cargo.toml, crossbeam-epoch/Cargo.toml, crossbeam-epoch/src/lib.rs, crossbeam-utils/Cargo.toml, crossbeam-utils/src/lib.rs
This module will require additional dep for soundness (https://github.com/crossbeam-rs/crossbeam/pull/1015), so split from APIs with default features.
This also help https://github.com/crossbeam-rs/crossbeam/pull/1075#issuecomment-2039050221 if we do it.
=> utils: Move atomic module behind atomic feature

Cargo.toml, ci/check-features.sh, crossbeam-utils/Cargo.toml, crossbeam-utils/README.md, crossbeam-utils/src/sync/once_lock.rs
Non-controversial part of https://github.com/crossbeam-rs/crossbeam/pull/1156.
(I actually have a [use case that needs this](https://github.com/taiki-e/portable-atomic/blob/29824b938b87585a7fa1ff3a7f14786f07a11ade/Cargo.toml#L88).)
=> Relax MSRV of utils to 1.56

.github/workflows/ci.yml, crossbeam-utils/Cargo.toml, crossbeam-utils/build.rs, crossbeam-utils/src/atomic/atomic_cell.rs, crossbeam-utils/tests/atomic_cell.rs
This fixes UB when lock-free and the value has uninitialized bytes, by using [atomic-maybe-uninit](https://github.com/taiki-e/atomic-maybe-uninit) crate.
Fixes #315
Fixes #748
Also, this makes 128-bit atomics lock-free on some platforms.
Closes https://github.com/crossbeam-rs/rfcs/issues/13
Currently, this patch always uses fallback (seqlock) on environments that do not support inline assembly, such as Miri.
It is possible to use atomic-maybe-uninit crate to fix UB of concurrent access with volatile read/write in seqlock/deque (#744, #859), but that is not included in this PR and is left to subsequent PRs.
---
cc @RalfJung
=> AtomicCell: Use atomic-maybe-uninit

crossbeam-skiplist/src/lib.rs
Noticed a small typo when reading skiplist documentation.
=> skiplist: typo use-after-free

.github/workflows/ci.yml
setup-cross-toolchain-action now supports this: https://github.com/taiki-e/setup-cross-toolchain-action/releases/tag/v1.27.0
Related: https://github.com/crossbeam-rs/crossbeam/pull/1169
=> ci: Test armv7hf Linux on ubuntu-24.04-arm runner

.github/workflows/ci.yml
See https://github.com/rust-lang/rust/issues/135867.
At the moment we are only seeing this problem with stable (1.84), but use ubuntu-22.04-arm in other toolchains as well just in case.
=> ci: Use ubuntu-22.04-arm instead of ubuntu-24.04-arm

Cargo.toml, crossbeam-channel/Cargo.toml, crossbeam-channel/tests/array.rs, crossbeam-channel/tests/list.rs, crossbeam-channel/tests/zero.rs, crossbeam-deque/Cargo.toml, crossbeam-deque/tests/fifo.rs, crossbeam-deque/tests/injector.rs, crossbeam-deque/tests/lifo.rs, crossbeam-epoch/Cargo.toml, crossbeam-epoch/examples/sanitize.rs, crossbeam-queue/Cargo.toml, crossbeam-queue/tests/array_queue.rs, crossbeam-queue/tests/seg_queue.rs, crossbeam-skiplist/Cargo.toml, crossbeam-utils/Cargo.toml, crossbeam-utils/tests/sharded_lock.rs
=> Replace rand dev-dependency with fastrand

crossbeam-epoch/src/atomic.rs
When https://github.com/crossbeam-rs/crossbeam/pull/796 was added, `int_to_ptr_with_provenance` was a new idea and looked like a hack. Now that strict provenance is stable, this is called `with_addr` and looks like a very normal API. ;)  And in fact, there's an even nicer API on top of it, `map_addr`. We can't use it here yet since the MSRV of Rust 1.61 does not have the strict provenance API, but we can still update code and comments to match the state of the art and to make it easier to eventually use the standard APIs.
=> replace int_to_ptr_with_provenance by map_addr-style function

crossbeam-channel/src/flavors/list.rs
This PR is fixing a regression introduced by #1084 that can lead to a double free when dropping the channel.
The method `Channel::discard_all_messages` has the property that if it observes `head.block` pointing to a non-null pointer it will attempt to free it.
The same property holds for the `Channel::drop` method and so it is critical that whenever `head.block` is freed it must also be set to a null pointer so that it is freed exactly once.
Before #1084 the behavior of `discard_all_messages` ensured `head.block` was `null` after its execution due to the atomic store right before exiting [1].
After #1084 `discard_all_messages` atomically swaps the current value of `head.block` with a null pointer at the moment the value is read instead of waiting for the end of the function.
The problem …
=> crossbeam-channel: prevent double free on `Drop`
